const shows = [ { venue: 'Fox Theater',
    title: [ 'Tove Lo', ' Phoebe Ryan' ],
    headliner: 'Tove Lo',
    date: '2017-02-08',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'As anyone with ears will tell you, Sweden is quite good when it comes to fostering amazing pop talent. With Stockholm’s , however, the typical mould of elegant heartfelt electropop has been beautifully corrupted by the sort of lyrical honesty and rawness that not only ruffles feathers, but makes you want to clutch your hand to your chest and wail along at the top of your lungs. Having self-released two examples of her unique take on pop – the clattering blood-letting of Love Ballad and the raw, but disarmingly melodic Habits (the latter earning respect from everyone from Pitchfork to Popjustice) – Tove Lo is ready to take her pop confessionals to a whole new level.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1478108370/event-6855342.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005155CC4786FE%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ '9-JhfFo7pMo', '1Zfmvc4CGbQ' ],
    similarArtists: [ 'Dua Lipa', 'Banks', 'Lady Gaga', 'Zara Larsson', 'JoJo' ] },
  { venue: 'Fox Theater',
    title: [ 'Rebelution', ' Passafire' ],
    headliner: 'Rebelution',
    date: '2017-02-10',
    startTime: '8:30',
    cost: 35,
    artistSummary: 'A dozen years into ’s stirring career, the release of the California reggae band’s fifth album FallingInto Place finds them more energized than ever. Touring relentlessly since 2014’s Count Me In debuted at No. 1on the Billboard Reggae chart, the band’s members have expanded their songwriting horizons and recorded 11tight new tracks that fuse an ever-youthful attitude of celebration with the mature perspective of men of the world.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479260420/event-6966887.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005169D1E0504A%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'eNIfTuUaglA', 'r5QP205XsFA' ],
    similarArtists:
     [ 'Iration',
       'Tribal Seeds',
       'The Expendables',
       'Slightly Stoopid',
       'Stick Figure' ] },
  { venue: 'Fox Theater',
    title: [ 'Russ' ],
    headliner: 'Russ',
    date: '2017-02-16',
    startTime: '8:00',
    cost: 29,
    artistSummary: 'As the truism goes, there are 10 years of hard work behind every overnight success. In an industry filled with plants and manufactured hype,  did it all himself. No deep-pocketed managers funded his ascent. No co-signs propelled his rise.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1485815106/event-7287303.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C00522D9FA14849',
    youTube: [ 'rkyzlXAYLQY', 'BD5a0ujoZZY' ],
    similarArtists: [ 'Post Malone', 'Jalen Santoy', 'Ishdarr', 'Logic', 'Bas' ] },
  { venue: 'Fox Theater',
    title:
     [ 'My Favorite Murder w/ Karen Kilgariff',
       ' Georgia Hardstark' ],
    headliner: 'My Favorite Murder w/ Karen Kilgariff',
    date: '2017-02-17',
    startTime: '8:00',
    cost: 29,
    artistSummary: 'Ready yourself for a murder adventure hosted by Karen Kilgariff and Georgia Hardstark, two lifelong fans of true crime stories. Each episode the girls tell each other their favorite tales of murder, and hear hometown crime stories from friends and fans. Check your anxiety at the door, cause Karen & Georgia are dying to discuss death.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481569001/event-7101727.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005187AB7A28F5%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [],
    similarArtists: [] },
  { venue: 'Fox Theater',
    title:
     [ 'Experience Hendrix with Billy Cox',
       ' Buddy Guy',
       ' Zack Wylde + More' ],
    headliner: 'Experience Hendrix with Billy Cox',
    date: '2017-02-24',
    startTime: '8:00',
    cost: 59,
    artistSummary: 'THE MUSIC OF JIMI HENDRIX COMES TO LIFE IN ‘EXPERIENCE HENDRIX TOUR’ ALL-STAR CONCERT SERIES!',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1475176696/event-6705134.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C00513AC08963E1%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'TuonBRZcJ4o', 'nbzYNoqU1T0' ],
    similarArtists: [] },
  { venue: 'Fox Theater',
    title: [ 'Vince Staples', ' Kilo Kish' ],
    headliner: 'Vince Staples',
    date: '2017-02-25',
    startTime: '7:00',
    cost: 27,
    artistSummary: 'is an American rapper from Long Beach, California. He is one-third of the Hip hop group Cutthroat Boyz, alongside fellow California rappers Joey Fatts, and Aston Matthews. Staples is currently signed to Blacksmith Records, A.G., ARTium Recordings and Def Jam Recordings. He came to prominence with his appearances on albums by Odd Future members and his collaborative mixtape titled Stolen Youth, with fellow American rapper Mac Miller, who produced the entire project. In October 2014, he released his debut EP Hell Can Wait, which included the singles "Hands Up" and "Blue Suede". His debut album, Summertime \'06, was released on June 30, 2015, to rave reviews. He was also chosen as part of the XXL Magazine 2015 Freshman Class.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1478888511/event-6947948.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005168D4AE32E3',
    youTube: [ 'qo9KTlElc00', 'zmFTCCq6xNc' ],
    similarArtists:
     [ 'Earl Sweatshirt',
       'ScHoolboy Q',
       'Isaiah Rashad',
       'Danny Brown',
       'Mick Jenkins' ] },
  { venue: 'Fox Theater',
    title: [ 'Ty Segall', ' Shannon and The Clams', ' White Fence', ' Axis' ],
    headliner: 'Ty Segall',
    date: '2017-02-27',
    startTime: '6:00',
    cost: 25,
    artistSummary: 'is a garage rock maestro that has been releasing music at a constant rate since 2008. He has become more recognizable to mainstream crowds in recent years with a string of successful albums with several different projects. His most recent album Emotional Mugger was released early this year and has continued to showcase his musical talent and the musicians that surround him.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479061583/event-6957495.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005168CFEF3158',
    youTube: [ 'WFcgehnpuOI', 'HUW-z5dLLrM' ],
    similarArtists:
     [ 'Ty Segall Band',
       'Thee Oh Sees',
       'Ty Segall & White Fence',
       'Ty Segall & Mikal Cronin',
       'Fuzz' ] },
  { venue: 'Fox Theater',
    title: [ 'Billy Crystal' ],
    headliner: 'Billy Crystal',
    date: '2017-03-01',
    startTime: '8:00',
    cost: 65,
    artistSummary: 'Tony® and Emmy Award®-winning comedian, actor, producer, writer and director  today will bring Spend the Night with Billy Crystal to the Fox Theater! Coming off the heels of his recent critically-acclaimed Australian tour, Crystal promises a hilarious and intimate evening.\n“This show is unique. There’s stand up, and ‘sit down’ which gives me great freedom to tell stories, show film clips and talk about my life and career and the world as I see it,” said Crystal. “It’s loose, unpredictable and intimate. The most fun I’ve had on stage in a long time.”\nA stand-up comic turned television star, Crystal found fame as a movie funnyman with starring roles in blockbusters such as When Harry Met Sally, City Slickers and Analyze This. He was much loved as the acclaimed nine-time host of the Academy Awards, an achievement topped only by Bob Hope, who hosted the Oscars 19 times. Also an award winning author, Crystal’s latest memoir, Still Foolin’ ‘Em: Where I’ve Been, Where I’m Going, and Where the Hell Are My Keys? was an instant NY Times best seller.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484249645/event-7259779.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005229ED623BAB%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'Qp2Tk4Zr2Ho', 'k2glgmIWjRQ' ],
    similarArtists:
     [ 'Rodney Dangerfield',
       'Ray Romano',
       'Redd Foxx',
       'Steve Harvey',
       'Wanda Sykes' ] },
  { venue: 'Fox Theater',
    title: [ 'Tchami', ' Mercer' ],
    headliner: 'Tchami',
    date: '2017-03-14',
    startTime: '8:00',
    cost: 25,
    artistSummary: 'Over the course of his career,  has managed to build a prolific reputation as one of the most sensational artists of his generation. From releasing his critically acclaimed EP ‘After Life’, his debut on BBC Radio 1’s Essential Mix, to performing at Coachella with a live choir in just one short year, it’s been clear to see that Tchami’s success is only continuing to flourish. With his burgeoning record label Confession persistently churning out hit records, it’s only still the beginning for Tchami as he sets his sights and sounds for 2017 to expand his empire of Future House.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481679259/event-7107951.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005189A8413B91',
    youTube: [ 'IGzBTQaHLpk', 'g36n4DtMqvg' ],
    similarArtists: [ 'Oliver Heldens', 'Pep & Rash', 'Curbi', 'Hi-Lo', 'Don Diablo' ] },
  { venue: 'Fox Theater',
    title: [ 'Lettuce', ' The Floozies', ' The Russ Liquid Test' ],
    headliner: 'Lettuce',
    date: '2017-03-17',
    startTime: '7:30',
    cost: 29,
    artistSummary: 'For more than two decades,  have brought a new vitality to classic funk, matching their smooth and soulful grooves with a hip-hop-inspired urgency and mastery of beat. Now, on their fourth studio album Crush, drummer Adam Deitch, guitarists Adam Smirnoff and Eric Krasno, bassist Erick “Jesus” Coomes, keyboardist Neal Evans, saxophonist Ryan Zoidis, and trumpet player Eric Bloom deepen that sound by channeling the sonic freedom and infectious energy of their incendiary live show.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1480359631/event-7024042.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005177B1954B01',
    youTube: [ 'SkJvRmMAEzc', 'E5mWN8z3Xxk' ],
    similarArtists:
     [ 'Soulive',
       'The Motet',
       'Dumpstaphunk',
       'The Greyboy Allstars',
       'The New Mastersounds' ] },
  { venue: 'Fox Theater',
    title: [ 'Lake Street Dive', ' Joey Dosik' ],
    headliner: 'Lake Street Dive',
    date: '2017-03-18',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'The title Side Pony takes its name from a song on the record that refers to a whimsical hairstyle, but it also serves as a metaphor for ’s philosophy and personality as a band. As Kearney puts it, “When we were settling on the album title, that one just stuck out to us as embodying the band’s spirit. We’ve always been this somewhat uncategorizable, weird, outlying, genre-less band. That’s the statement we wanted to make with this record: be yourself.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479514967/event-6966889.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005163E84E7D69%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'cZKJp8Yjcd4', '0LhsE-uqqE0' ],
    similarArtists:
     [ 'St. Paul & The Broken Bones',
       'The Suffers',
       'Anderson East',
       'Allen Stone',
       'Leon Bridges' ] },
  { venue: 'Fox Theater',
    title: [ 'The Kills' ],
    headliner: 'The Kills',
    date: '2017-03-22',
    startTime: '8:00',
    cost: 37,
    artistSummary: 'During the past few years she admits to having penned somewhere around 120 songs. But writing has never been a problem for Mosshart, who composes quickly and fearlessly, rarely overthinking, just letting the songs move through her, inspired by an overheard conversation, a mood, a person, or just the sound her turn indicator makes while she is guiding her muscle car through traffic. What takes the most time is writing separately and turning it into a cohesive whole. Mosshart expounds, “If ‘Ash & Ice’ were a painting, it would be incredibly complex. It would be one that looked like it had been painted over and over and over and over. It would be so thick off the wall, it would be coming through the frame.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479515199/event-6966890.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C00516BB8764195%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'zZXqBfd0F68', '8T2Vb9Q43Zg' ],
    similarArtists:
     [ 'The Dead Weather',
       'Blood Red Shoes',
       'The White Stripes',
       'The Last Shadow Puppets',
       'Black Rebel Motorcycle Club' ] },
  { venue: 'Fox Theater',
    title: [ 'Marc Maron' ],
    headliner: 'Marc Maron',
    date: '2017-03-24',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'For over twenty years,  has been writing and performing raw, honest and thought- provoking comedy for print, stage, radio, online and television. A legend in the stand-up community, Maron has appeared on many television talk shows, including DavidLetterman, Craig Ferguson, Jimmy Fallon, Jimmy Kimmel, Seth Meyers, Charlie Rose and Bill Maher. He has appeared on Conan O’Brien more than any other comedian.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481569168/event-7101739.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005187A4322668%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ '8G4t_YPoAjM', 'zVnObCXa18A' ],
    similarArtists:
     [ 'You Made It Weird with Pete Holmes',
       'nerdist',
       'Bill Burr',
       'Doug Benson',
       'Joe Rogan' ] },
  { venue: 'Fox Theater',
    title: [ 'Passenger' ],
    headliner: 'Passenger',
    date: '2017-03-30',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'With his new album Young As The Morning Old As The Sea set for release on September 23rd, UK singer/songwriter  has announced a North American headline tour starting on March 7, 2017.  Known for holding the attention of thousands of fans at any given live show with only his distinct voice, engaging storytelling and acoustic guitar, Passenger has also revealed that for the first time he’ll be joined by a full, four-piece band.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1472848837/event-6177418.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C0050E7DC835650%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'otFmtLe9NvM', 'xnZDDH-NMt4' ],
    similarArtists:
     [ 'Mumford & Sons',
       'Stu Larsen',
       'Ben Howard',
       'Vance Joy',
       'The Lumineers' ] },
  { venue: 'Fox Theater',
    title: [ 'Peppa Pig Live!' ],
    headliner: 'Peppa Pig Live!',
    date: '2017-04-02',
    startTime: '3:00',
    cost: 17,
    artistSummary: 'More fun than a muddy puddle! Peppa Pig is hitting the road for her first-ever U.S. theatrical tour, Peppa Pig’s Big Splash. The original production features Peppa, George, and all their friends in an all-singing, all-dancing adventure full of songs, games and muddy puddles!',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1473875341/event-6571021.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005127F924EDAB%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'SH5bWAFh690', 'uBZ-4Q9h6EY' ],
    similarArtists: [] },
  { venue: 'Fox Theater',
    title: [ 'Richard Ashcroft (Of the Verve)' ],
    headliner: 'Richard Ashcroft (Of the Verve)',
    date: '2017-04-05',
    startTime: '8:00',
    cost: 45,
    artistSummary: 'Richard Ashcroft is the essence of Brit Cool. Like Syd Barrett or Nick Drake before him, Pete Doherty and Alex Turner after him, Ashcroft is one of those rarified rock eccentrics; the type of visionary spirit that’s one of England’s greatest musical exports. As the frontman of The Verve, Ashcroft was the signature voice of 1990s English pop music. The band’s global megahit “Bittersweet Symphony” – which Chris Martin famously called “the best song ever written, sung by the best singer in the world” – made them stars in the States and heroes at home. He’s played Saturday Night Live, graced the cover of Rolling Stone, been nominated for VMAs, GRAMMY’s, and The Mercury Prize but he’s never made a soul record with a hot shot hip-hop producer and venerated Motown greats, until now. In 2009, Ashcroft disbanded The Verve and focused on writing songs inspired by his love of soul, funk and gospel. The result is his first solo album in four years, United Nations Of Sound.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481569315/event-7101748.png',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005186A35D2FFD%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [],
    similarArtists: [] },
  { venue: 'Fox Theater',
    title: [ 'Bonobo' ],
    headliner: 'Bonobo',
    date: '2017-04-12',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'Simon Green aka  is back with his sixth album – the masterful, magisterial “Migration” – is a record which cements his place in the very highest echelons of electronic music and beyond. By turns lush, manic, beautiful, melancholy, joyful, packed with both emotion and technical skill, this is perhaps his most ambitious attempt yet to capture the very textures of human existence in his work, as Green says of the broad dynamics on the album, “Life has highs, lows, loud and quiet moments, beautiful ones and ugly ones. Music is a reflection of life.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484769275/event-7287304.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005226E21230A6',
    youTube: [ 'Ca93bp-jpn8', 'fQAFfeQNpGc' ],
    similarArtists:
     [ 'Mechanical Me',
       'Emancipator',
       'The Cinematic Orchestra',
       'Thievery Corporation',
       'Pilote' ] },
  { venue: 'Fox Theater',
    title: [ 'The New Pornographers', ' Waxahatchee' ],
    headliner: 'The New Pornographers',
    date: '2017-04-13',
    startTime: '8:00',
    cost: 38,
    artistSummary: 'Whiteout Conditions, the new full-length record from critically acclaimed supergroup , is due April 7. The album is the first release on the band’s own Collected Works Records imprint, in partnership with Concord Records.\nOf writing the new record, founder and frontman A.C. Newman notes that, “At the beginning of this record, there was some thinking that we wanted it to be like a Krautrock Fifth Dimension. Of course, our mutated idea of what Krautrock is probably doesn’t sound like Krautrock at all. But we were thinking: Let’s try and rock in a different way.”\nSince their debut in 2000, The New Pornographers have released six studio albums including their most recent, Brill Bruisers, hailed as an “exuberant, synthpop-infused set” by Rolling Stone, “infectious” by Harper’s Bazaar and “the grand and purposeful hookfest that you would hope these guys would come back with” by Stereogum. Pitchfork went on to note that “with the futurist sound of Brill Bruisers, the whole band embraces a more electric version of itself— bulked-up in chrome-plated armor, firing on all cylinders, and ready to steamroll anything in its path.” The band celebrated the release with a special NPR Music “First Listen Live” concert at the legendary Brill Building, and performed songs from the album on both “Conan” and the “Late Show with David Letterman.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1485908838/event-7372056.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C00523EB4C02D9D%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet%23efeat4211',
    youTube: [ 'WSsOEUlfsKk', 'sMie-Pi1YSM' ],
    similarArtists: [ 'A.C. Newman', 'Destroyer', 'Spoon', 'Sloan', 'Wolf Parade' ] },
  { venue: 'Fox Theater',
    title: [ 'Coheed and Cambria', ' The Dear Hunter' ],
    headliner: 'Coheed and Cambria',
    date: '2017-04-14',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'The multi-dimensional, progressive-rock band,  announced today that they will be touring the US this spring, performing their landmark third album, “Good Apollo, I’m Burning Star IV: From Fear Through The Eyes of Madness”, in its entirety.\nGood Apollo, The epic 72-minute recording considered by most as the bands most progressive album, and including two of the band’s most known singles (Welcome Home and The Suffering) and selling over a million records worldwide. The band’s legion of fans grows every year, and the NEVERENDER concept now holds a special place within the culture of the Coheed community. NEVERENDER is the moniker given to these album performances by the band and it first started in 2008, when Coheed performed their first 4 albums over 4 nights – completing the feat in 4 different cities – New York, London, Chicago and Los Angeles. The band’s concept albums lend themselves particularly well to the live setting.\nSimultaneously, singer Claudio Sanchez announced on CBR.com (Comic Book Resources) his plans to release a 12-issue comic book for “Good Apollo” as part of his The Amory Wars series which comes this spring from Boom! Studios. The story, which loosely follows the lyrics of the album, centers around protagonist Claudio Kilgannon and the shocking discovery that he is The Crowing, a entity prophesied about in the holy book, who must dole out God’s judgment to destroy the universe.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1485313402/event-7333174.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005237D9875B63',
    youTube: [ 'PQxOdDPaNkY', 'kq3aWRYlEdI' ],
    similarArtists:
     [ 'The Prize Fighter Inferno',
       'The Dear Hunter',
       '3',
       'Closure in Moscow',
       'Thank You Scientist' ] },
  { venue: 'Fox Theater',
    title: [ 'Bill Maher' ],
    headliner: 'Bill Maher',
    date: '2017-04-22',
    startTime: '8:00',
    cost: 65,
    artistSummary: 'For more than twenty years,  has set the boundaries of where funny, politicaltalk can go on American television. First on “Politically Incorrect” (Comedy Central, ABC,1993-2002), and for the last fourteen years on HBO’s “Real Time,” Maher’s combination of unflinching honesty and big laughs have garnered him 38 Emmy nominations. Maher won his first Emmy in 2014 as executive producer for the HBO series, “VICE.” In October of 2008, this same combination was on display in Maher’s uproarious and unprecedented swipe at organized religion, “Religulous,” directed by Larry Charles (“Borat”). The documentary has gone on tobecome the 8th Highest Grossing Documentary ever.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479260423/event-6966891.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C00516BCACE4CC0%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'hqtbMr1dZYU', 'VB7pUe6jNTI' ],
    similarArtists:
     [ 'Lenny Bruce',
       'Sam Kinison',
       'Noam Chomsky',
       'Dylan Moran',
       'David Sedaris' ] },
  { venue: 'Fox Theater',
    title: [ 'Deadmau5' ],
    headliner: 'Deadmau5',
    date: '2017-04-24',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'Joel Zimmerman, more commonly known as deadmau5 (pronounced ‘dead mouse’), is one of the world’s most respected electronic music producers of modern times. Enjoying international chart success with his singles “Professional Griefers,” “Sofi Needs A Ladder,” “Ghosts ‘n’ Stuff” and “I Remember,” he has also released five critically acclaimed albums. The multiple JUNO Award-winning and GRAMMY®-nominated artist performed at the 54th Annual GRAMMY Awards as part of its first ever telecast performance highlighting electronic music. He appeared on the cover of Rolling Stone (summer double issue, 2012), marking him as the first electronic artist to do so. His ability to push the boundaries of his talent grows at an equal rate to his fan base, which counts over 15 million over his combined social media channels. Earlier this year deadmau5 leaped into the virtual reality realm with Absolute and released a massive sample catalog with Splice, while performing major festival plays throughout the world. Look for more exciting things to come from deadmau5 soon.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1480964785/event-7056246.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fticketmaster.com%2Fevent%2F1C00517E9DFE29F0%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ '2mBa6_mwHq0', 'GTCqeWu094I' ],
    similarArtists:
     [ 'Melleefresh vs. Deadmau5',
       'BSOD',
       'deadmau5 & Wolfgang Gartner',
       'deadmau5 & Kaskade',
       'Feed Me' ] },
  { venue: 'Fox Theater',
    title: [ 'Deadmau5' ],
    headliner: 'Deadmau5',
    date: '2017-04-25',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'Joel Zimmerman, more commonly known as deadmau5 (pronounced ‘dead mouse’), is one of the world’s most respected electronic music producers of modern times. Enjoying international chart success with his singles “Professional Griefers,” “Sofi Needs A Ladder,” “Ghosts ‘n’ Stuff” and “I Remember,” he has also released five critically acclaimed albums. The multiple JUNO Award-winning and GRAMMY®-nominated artist performed at the 54th Annual GRAMMY Awards as part of its first ever telecast performance highlighting electronic music. He appeared on the cover of Rolling Stone (summer double issue, 2012), marking him as the first electronic artist to do so. His ability to push the boundaries of his talent grows at an equal rate to his fan base, which counts over 15 million over his combined social media channels. Earlier this year deadmau5 leaped into the virtual reality realm with Absolute and released a massive sample catalog with Splice, while performing major festival plays throughout the world. Look for more exciting things to come from deadmau5 soon.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1480964818/event-7056247.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fticketmaster.com%2Fevent%2F1C00517E9E0229FB%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ '2mBa6_mwHq0', 'GTCqeWu094I' ],
    similarArtists:
     [ 'Melleefresh vs. Deadmau5',
       'BSOD',
       'deadmau5 & Wolfgang Gartner',
       'deadmau5 & Kaskade',
       'Feed Me' ] },
  { venue: 'Fox Theater',
    title: [ 'Deadmau5' ],
    headliner: 'Deadmau5',
    date: '2017-04-26',
    startTime: '8:00',
    cost: 35,
    artistSummary: 'Joel Zimmerman, more commonly known as deadmau5 (pronounced ‘dead mouse’), is one of the world’s most respected electronic music producers of modern times. Enjoying international chart success with his singles “Professional Griefers,” “Sofi Needs A Ladder,” “Ghosts ‘n’ Stuff” and “I Remember,” he has also released five critically acclaimed albums. The multiple JUNO Award-winning and GRAMMY®-nominated artist performed at the 54th Annual GRAMMY Awards as part of its first ever telecast performance highlighting electronic music. He appeared on the cover of Rolling Stone (summer double issue, 2012), marking him as the first electronic artist to do so. His ability to push the boundaries of his talent grows at an equal rate to his fan base, which counts over 15 million over his combined social media channels. Earlier this year deadmau5 leaped into the virtual reality realm with Absolute and released a massive sample catalog with Splice, while performing major festival plays throughout the world. Look for more exciting things to come from deadmau5 soon.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481138397/event-7066142.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005181CD8C',
    youTube: [ '2mBa6_mwHq0', 'GTCqeWu094I' ],
    similarArtists:
     [ 'Melleefresh vs. Deadmau5',
       'BSOD',
       'deadmau5 & Wolfgang Gartner',
       'deadmau5 & Kaskade',
       'Feed Me' ] },
  { venue: 'Fox Theater',
    title: [ 'The Magnetic Fields', ' 50 Song Memoir ' ],
    headliner: 'The Magnetic Fields',
    date: '2017-04-30',
    startTime: '8:00',
    cost: 39,
    artistSummary: 'will be performing in support of their forthcoming multi-disc album, 50 Song Memoir, to be released Spring 2017 on Nonesuch Records. This 50-song series will be performed over two nights (songs 1-25 on night #1, songs 26-50 on night #2).',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1476912660/event-6835789.jpg',
    link: 'http://ticketmaster.evyy.net/c/253185/264167/4272?u=http%3A%2F%2Fwww.ticketmaster.com%2Fevent%2F1C005146DAC2786A%3Fcamefrom%3DCFC_ANOTHERPLANET_web%26brand%3Danotherplanet',
    youTube: [ 'yWf54uGWgWA', 'U3nm0_3yJjw' ],
    similarArtists:
     [ 'The 6ths',
       'Stephin Merritt',
       'Future Bible Heroes',
       'The Gothic Archies',
       'The Mountain Goats' ] },
       { venue: 'The Chapel',
    title: [ 'Hibbity Dibbity', ' Whiskerman', ' Big Sticky Mess' ],
    headliner: 'Hibbity Dibbity',
    date: '2017-02-03',
    startTime: '8:00',
    cost: 18,
    artistSummary: 'Hibbity Dibbity is a dance rock n\' roll group from San Francisco. They blend together sounds and styles from numerous genres to create feel-good music that will move you. They are clever, ecstatic, and riotous. Timeless, but kinda dirty. Pelting rhythms that make your feet move. Their new single “Touchy Feely," is a happy tune with a swoon-worthy chorus. Super tight; then loose in all the right places.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1477951375/event-6880220.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1377268%2Ftfly',
    youTube: [ '4dXun2TYjDs', 'Yw-eOzmc3lg' ],
    similarArtists: [ 'The Jag', 'Nigel Hall', 'Wolf!', 'Daniel T.', 'Raw Poetic' ] },
  { venue: 'The Chapel',
    title: [ 'Pop Rocks' ],
    headliner: 'Pop Rocks',
    date: '2017-02-04',
    startTime: '8:00',
    cost: 16,
    artistSummary: 'is a high energy rock / dance band celebrating 10 years of delivering it to you live -- from their hometown of San Francisco, to gigs across the country, playing nationally at parties, club dates and social events for folks who are looking for something fun, wild, and unapologetically over the top. Starting by accident, simply coming together for the fun of it for a "one off" gig at renowned SF venue Slim\'s, the band has stuck it out, come hell or high water, and grown to be one of the most in-demand bands playing today.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1474320320/event-6647664.jpg',
    link: 'https://www.ticketfly.com/purchase/event/1324851?_ga=1.12117942.380919874.1465500893&__utma=1.380919874.1465500893.1473699005.1474319733.9&__utmb=1.4.10.1474319733&__utmc=1&__utmx=-&__utmz=1.1470940265.6.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utm',
    youTube: [ 'WRj_5C3bD1w', 'hwpJmpmBLN8' ],
    similarArtists:
     [ 'Future Movement',
       'Toothpick',
       'Philippe Maurice',
       'House Of Whacks',
       'wulf n\'bear' ] },
  { venue: 'The Chapel',
    title: [ 'Super Bowl LI Live on the Chapel\'s 24 ft Screen!' ],
    headliner: 'Super Bowl LI Live on the Chapel\'s 24 ft Screen!',
    date: '2017-02-05',
    startTime: '2:30',
    cost: NaN,
    artistSummary: 'The Atlanta Falcons are back after a 19 year Super Bowl drought to take on America\'s favorite villains, the New England Patriots.This will be a full venue Super Bowl Sunday like you\'ve never seen - Super Bowl worthy drinks, an amazing themed menu from our head chef, and of course we\'ll be screening this on our 24 ft screen! NO COVER! The bar opens at 11am, venue at 2pm – which means we\'re gearing up for an all day party!Let us take care of the pre-game prep and the post-game cleanup, while you just focus on the important things: eating, drinking, and celebrating our favorite pastime.And remember - space is limited, so this will be a first come first served event. See you Sunday!',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1485909114/event-7341882.jpg',
    link: null,
    youTube: [ 'BCbt81C-Z8o', 'dlrTXh63VSY' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'Surfer Blood', ' Boogarins' ],
    headliner: 'Surfer Blood',
    date: '2017-02-07',
    startTime: '8:00',
    cost: 18,
    artistSummary: 'began recording and touring immediately behind their infectious debut, Astro Coast (2010) and quickly took over almost the entire world (except for the deepest realms of the ocean and really, really cold places). The group followed suit with the Tarot Classics EP (2011), Pythons (2013) and 1000 Palms (2015). Surfer Blood have performed in 5 continents, toured with heroes like The Pixies and Guided By Voices, played on TV, at Coachella and giant festivals throughout the world, while also occasionally plugging in their amps at all-ages house parties. Surfer Blood are the cleanest and nicest band in existence.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481829944/event-7112289.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1399386%2Ftfly',
    youTube: [ 'wSVXPvXb10M', '4WVqA8abnMc' ],
    similarArtists:
     [ 'Smith Westerns',
       'Real Estate',
       'Mikal Cronin',
       'Beach Fossils',
       'Titus Andronicus' ] },
  { venue: 'The Chapel',
    title: [ 'Mr. Elevator' ],
    headliner: 'Mr. Elevator',
    date: '2017-02-08',
    startTime: '8:00',
    cost: 15,
    artistSummary: 'T\'was from the sands of Laguna Beach where Tomas & Wyatt and fellow Elevator repair service collegue met through a dolphin\'s cry in the midst of the night, waning-moon present and shimmering across the moonlit sea. The 3 most watery human beings then started to "jam" as a guitar-less mind exploration voyage through the realms of time and space itself. Through their arduous adventures an EP was conceived.. "Staring at the Sun.", about the mind and how a human being can go through stages of love & post-psychotic-ness. They have lately returned to live and frolic in and out of the sepultural smog of los angeles, currently working on more tantalizing tunes towards a full length LP to be released in the next coming of moon phases.... Mr.Elevator & the Brain Hotel.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484768042/event-7287693.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1418249%2Ftfly',
    youTube: [ 'aT5mbBAwjs4', 'Ie_h7oRq6KE' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'John Brothers Piano Company', ' Tumbledown House' ],
    headliner: 'John Brothers Piano Company',
    date: '2017-02-09',
    startTime: '7:30',
    cost: 15,
    artistSummary: 'The innovative sounds of The  are the colors of timeless energy – early jazz meets stride and swing. But the definitive quality of this dynamic quartet does lies not just in genres they bend or blend, but in a strong notion that the audience has been the primary inspiration in the development of their sound.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484085022/event-7241795.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1413529%2Ftfly',
    youTube: [ '3ZzynuIKnh4', 'TtrPnGJYbSI' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'Sex With Eugene' ],
    headliner: 'Sex With Eugene',
    date: '2017-02-10',
    startTime: '7:00',
    cost: 12,
    artistSummary: 'Just when you may have fatefully assumed that the wildly inappropriate SEX WITH EUGENE was restricted to the confines of OZY, we offer you for the first time ever an evening of intelligent and wildly inappropriate conversation with OZY\'s Editor-at-Large Eugene S. Robinson. Part variety show, part paneled talk show, part Q&A, this live event will get to the heart of your sex struggles and your sexy struggles just in time for Valentine’s Day. OZY is something that doesn\'t just happen on a phone or a laptop screen. It lives beyond the confines of its digital framework and is very much informed by real people with real interests in real spaces. And its signature sex and love advice column, SEX WITH EUGENE, written and conceived by OZY Editor-at-Large and bon vivant Eugene S. Robinson embodies that ethos with the first ever live event. Guests! Jennifer Locke: artist, fighter, and domme extraordinaire Allan MacDonell: author of Punk Elegies and Prisoner of X, a tome detailing his 20 years as executive editor at Hustler. Fauxnique: you ever win Trannyshack? As a female impersonator? Or as a female-female impersonator? Well, Fauxnique has. Jessica Drake: porn activist Bruce Lamont: Our Paul Schafer, the one-man-house band. Bruce\'s work with his band Yakuza, his side project with Scott Kelly from Neurosis, Brain Tentacles, or his crazy post-modern take on money making with Led Zeppelin 2, makes him and his sax the perfect fit for doing the musical honors.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1485803898/event-7341883.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1421292%2Ftfly',
    youTube: [ 'wE4vS0tO6iw', '-8qhXm4qvhI' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'Let It Bleed' ],
    headliner: 'Let It Bleed',
    date: '2017-02-11',
    startTime: '8:00',
    cost: 18,
    artistSummary: 'Dead Sara, with the help of producer Noah Shain, have figured that out on their second album, Pleasure To Meet You, delivering a powerful statement that just might make Grohl\'s prophecy come true. From the ferocious opening one-two punch of "Suicidal" and "LA City Slum," songs made to ignite an audience live, the Los Angeles-based quartet of singer Emily Armstrong, lead guitarist Siouxsie Medley, bassist Chris Null and drummer Sean Friday deliver a savage message to listeners that this is a band intent on fulfilling all of the promise of their first album. Mission accomplished. Armstrong says this is due, in large part, to the group\'s hard work on the road.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484168145/event-7250762.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1413907%2Ftfly',
    youTube: [ 'qTrGX_JUvSY', 'B0lC0I96zpE' ],
    similarArtists:
     [ 'all that ive got',
       'light with the sharpened edge-',
       'yesterday feelings',
       'Cut Up Angels',
       'soundeffects and overdramatics' ] },
  { venue: 'The Chapel',
    title: [ 'Cory Hanson' ],
    headliner: 'Cory Hanson',
    date: '2017-02-12',
    startTime: '8:00',
    cost: 15,
    artistSummary: '',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1480963824/event-7043784.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1392639%2Ftfly',
    youTube: [ 'WHdTtoQHBSE', 'jumZ_Ru_BOM' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'White Lies', ' VOWWS' ],
    headliner: 'White Lies',
    date: '2017-02-14',
    startTime: '8:00',
    cost: 25,
    artistSummary: 'There are at least three artists who have used this name\n1. A popular indie band from London, England\n2. A singer from Belgium\n3. A rock band from Devon, England\n\n1) A three-piece London indie band formed from the ashes of Fear Of Flying in late 2007.  The line-up consists of singer/guitarist Harry McVeigh, bassist/lyricist Charles Cave and drummer Jack Brown. Unfinished Business (released April 29th 2007) was their first single, released on Jack Brown\'s label Chess Club Records.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479340106/event-6970922.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1383688%2Ftfly',
    youTube: [ 'vmc_ZHFCauI', 'GoR4Rzn5-pg' ],
    similarArtists:
     [ 'Editors',
       'The Cinematics',
       'Interpol',
       'Foals',
       'Kings of Leon' ] },
  { venue: 'The Chapel',
    title:
     [ 'Slim Cessna\'s Auto Club',
       ' Feral Ohms featuring Mr Ethan Miller',
       ' Sweet Chariot' ],
    headliner: 'Slim Cessna\'s Auto Club',
    date: '2017-02-15',
    startTime: '8:00',
    cost: 15,
    artistSummary: 'SLIM CESSNA’S AUTO CLUB The Commandments According to SCAC\n\nIn September 2016, Slim Cessna\'s Auto Club is releasing its new album The Commandments According to SCAC. It has been twenty-four years since Slim Cessna parted ways with The Denver Gentlemen, that grand progenitor of the peculiar strain of Gothic Americana unique to the Mile High City, to form Slim Cessna\'s Auto Club with a group of talented peers. \nMany bands with a long and successful run like that would stick close to its roots. But rather than rest on well-earned laurels, the Auto Club challenged itself to break with well-worn modes of operating for the new record. \nWallace Stenger may have captured the spirit of the west in his 1971 novel Angle of Repose. Jim Thompson surely exposed the lurid underbelly of the Western experience. Cormac McCarthy definitely evoked the conflicted, tortured spirit of small town life on the frontier. William Faulkner and Flannery O\'Connor informed all of them with a humor and soulfulness. It is that literary tradition that imbues the harrowing and celebratory sound and riveting stories of Slim Cessna\'s Auto Club. And for a full twenty years it was largely in that realm of art that the Auto Club reveled and garnered a loyal cult following well beyond the boundaries of The Queen City of the Plains. \nBut no band can be satisfied with treading the same territory that it helped to define forever. The Commandments According to SCAC, will be the first full length album of original material released on the Auto Club\'s own imprint, SCACUNINCORPORATED. \nThe title evokes the themes of cosmic punishment and redemption that have served the band\'s songwriting engine so well in the past. But this set of songs sounds more hopeful and expansive, a quality that was always there but this time out the brighter sides of the songwriting are emphasized. Hints of this saw early full-flown expression on 2008\'s Cipher and Unentitled from 2011. \nWith The Commandments, however, the Auto Club seems to step forward into the promise of its own possibilities. It remains capable of the heady darkness and celebratory intensity with which it made its name. \nNow that charmingly dusky and spare sound breathes with a color and delicacy of feeling that perhaps sat in the background in times past. Maybe it\'s partly due to the greater creative contributions from longtime collaborator Rebecca Vera and The Peeler or the inclusion of upright bass player Ian O\'Dougherty. But the core of the band\'s songwriting and sound is anchored firmly in the vision of Slim, Munly Munly and Lord Dwight Pentacost. \nWhatever the true source of this transformation, The Commandments According to SCAC sounds like a band marshalling its creative inspiration to mark out a new chapter of its existence. When you get to see the Auto Club tour following the album\'s release, you\'ll get to see an already mighty band reinvigorated by this new spirit as well as by the fire that has long burned in its collective belly.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479340213/event-6963957.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1382837%2Ftfly',
    youTube: [ 'Vorr7ni7sNM', 'XRBrSDhyPX4' ],
    similarArtists:
     [ 'Jay Munly',
       'Munly & the Lee Lewis Harlots',
       'Tarantella',
       'Munly & the Lupercalians',
       'Those Poor Bastards' ] },
  { venue: 'The Chapel',
    title: [ 'Kan Wakan' ],
    headliner: 'Kan Wakan',
    date: '2017-02-16',
    startTime: '8:00',
    cost: 18,
    artistSummary: 'Kan Wakan is Gueorgui Linev, the producer, film composer, songwriter, and multi-instrumentalist whose critically acclaimed and Billboard-charting music dissolves the genre-breaking electronica of Massive Attack, Air, Bonobo and Zero 7 into a bottomless sea of 20th century minimalism, psychedelic soul and ambient atmosphere. The upcoming tour follows on the heels of Kan Wakan’s 2 new singles ahead of the new album, ‘I Would’ and ‘Molasses;’ both entering the Top 5 on Hype Machine charts and garnering significant airplay on BBC Radio 1 & 6, as well charting in the Top 10 on CMJ stations across the country. ‘Molasses’ in particular has sparked tremendous buzz, named “Today’s Top Tune” by KCRW, the track was synced on Oprah’s OWN Network show ‘Queen Sugar,’ aired Nov. 30th, and was licensed for a Dior Spring/Summer Ad. 2017 will mark a new chapter for the LA-based Bulgarian-born musician who was recently named in the LA Weekly as "one of the top 10 young songwriters in Los Angeles". Having produced and worked with the likes of Moses Sumney and Thundercat and scored his first feature film “Dead Draw”, it was time to incorporate a few collaborations of his own. With triple LP ‘Phantasmagoria’ soon on the way, Kan Wakan’s upcoming work incorporates guest vocalists and collaborations into an immersive melding of organic and electronic production mixed in with the orchestral flourishes of the Sofia Philharmonic orchestra. The upcoming new album is rounded out with Kan Wakan’s signature cinematic soundscapes that explore the space from where ‘Moving On’ left off.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484085067/event-7241797.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1413426%2Ftfly',
    youTube: [ '6A5mgy-pYSk', '8Tb3ryvsfMc' ],
    similarArtists:
     [ 'Lena Fayre',
       'Bloom Twins',
       'Adna',
       'Arthur Beatrice',
       'Emile Haynie' ] },
  { venue: 'The Chapel',
    title: [ 'Noname', ' Ravyn Lenae' ],
    headliner: 'Noname',
    date: '2017-02-18',
    startTime: '5:30',
    cost: 15,
    artistSummary: '(born Fatimah Warner) is an American artist from Chicago, Illinois, who blurs the lines of poetry and rap through the music she creates.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1481569311/event-7101747.jpg',
    link: 'http://calendar.thebaybridged.com/events/2017/2/18/noname-show2',
    youTube: [ 'yE3N3Wp5dD4', 'MC2bJU4WwFY' ],
    similarArtists:
     [ 'Isaiah Rashad',
       'Chance the Rapper',
       'Saba',
       'Nxworries',
       'Mick Jenkins' ] },
  { venue: 'The Chapel',
    title: [ 'Noname', ' Ravyn Lenae' ],
    headliner: 'Noname',
    date: '2017-02-18',
    startTime: '8:30',
    cost: 15,
    artistSummary: '(born Fatimah Warner) is an American artist from Chicago, Illinois, who blurs the lines of poetry and rap through the music she creates.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479510825/event-6960622.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1383354%3F_ga%3D1.5549747.1886246706.1478123422',
    youTube: [ 'yE3N3Wp5dD4', 'MC2bJU4WwFY' ],
    similarArtists:
     [ 'Isaiah Rashad',
       'Chance the Rapper',
       'Saba',
       'Nxworries',
       'Mick Jenkins' ] },
  { venue: 'The Chapel',
    title: [ 'Meatbodies', ' CCR Headcleaner', ' Shame Waves' ],
    headliner: 'Meatbodies',
    date: '2017-02-19',
    startTime: '8:00',
    cost: 15,
    artistSummary: 'Meatbodies is a band consisting of Kevin Boog, Chad Ubovich, and Patrick Nolan.\n\nChad started the band in 2011 as a solo project called Chad and The Meatbodies one tape was put out by GOD? Records, and Soon after the name of the project was changed to simply “Meatbodies,” followed up by a full length LP for In The Red Records of the same name.\n\nAfter extensively touring on the album and tired of being a solo act Ubovich recruited his two friends and fellow song writers Kevin Boog, and Patrick Nolan.\n\n“the name was originally changed to just MEATBODIES with the intent of it becoming an actual ‘band’ one day. And now it is! so that’s great!”\n\nThe group is now charging on with a new 7” for Famous Class Records and their sophomore LP for In The Red due later this year.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1486153315/event-7394080.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1428125%2Ftfly',
    youTube: [ 'ZuernzZbitA', 'xJnBLpqrUGQ' ],
    similarArtists: [ 'Fuzz', 'Wand', 'Ty Segall', 'Thee Oh Sees', 'Ty Segall Band' ] },
  { venue: 'The Chapel',
    title:
     [ 'Desert Daze Caravan feat. Temples',
       ' Night Beats',
       ' Deap Valley' ],
    headliner: 'Desert Daze Caravan feat. Temples',
    date: '2017-02-22',
    startTime: '7:00',
    cost: 34,
    artistSummary: 'It doesn’t take too long with Temples’ second album Volcano to realise that a noticeable evolution has taken place, whilst still keeping intact all the things you loved about the band’s debut, Sun Structures. It’s there from the outset: the beefed-up beats of Certainty reveal an expanded sonic firmament, one in which bright synth hooks and insistent choruses circle around each other over chord sequences that strike just the right balance between nice and queasy. Shock-haired singer James says, “If there’s a sense of scale, it was really just a result of implementing a load of things that we didn’t know about the first time around.” Referring back to Sun Structures, a record that was recorded in his house in his native Kettering, James explains, “We didn’t even have a subwoofer to listen back to things that we did on Sun Structures, so there was nothing below 50Hz on Sun Structures. We didn’t even know those frequencies were there!” Co-founding member and bassist Thomas Warmsley describes a record in which “we discovered a lot as we went along, and the excitement at having done so radiates outwards.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484168663/event-7106399.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1401127%3Futm_medium%3Dbks',
    youTube: [ '_eNrPQnbOec', 'yAWZQcQvLk0' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'Moon Duo', ' Leaf Coach', ' Fine Points' ],
    headliner: 'Moon Duo',
    date: '2017-02-23',
    startTime: '8:00',
    cost: 16,
    artistSummary: 'Formed in San Francisco in 2009 by Wooden Shijps guitarist Ripley Johnson and Sanae Yamada, ’s first two critically acclaimed EPs, Killing Time (2009) and Escape (2010), fused the futuristic pylon hum and transistor reverb of Suicide or Silver Apples with the heat-haze fuzz of American rock ‘n’ roll to create tracks of blistering, 12-cylinder space rock.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479103798/event-6957634.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1379639%3Futm_medium%3Dbks',
    youTube: [ 'a-HLLWCKgHw', 'R-UouNlMK84' ],
    similarArtists:
     [ 'Wooden Shjips',
       'Psychic Ills',
       'Föllakzoid',
       'Lumerians',
       'The Warlocks' ] },
  { venue: 'The Chapel',
    title:
     [ 'Hanni El Khatib',
       ' The Buttertones',
       ' The Molochs',
       ' Innovative Leisure DJs ' ],
    headliner: 'Hanni El Khatib',
    date: '2017-02-24',
    startTime: '7:00',
    cost: 18,
    artistSummary: '’s first idea for his Savage Times project was to do something he’d never done before. Instead, he ended up doing … well, everything he’d never done before. He’d be playing new instruments, writing in unfamiliar new ways, opening himself up to an unrelenting stream of ideas and dedicating himself totally to pure musical instinct—and then releasing songs instantly to the public, without waiting to tour or assemble an album or anything. At the end of 2015, he’d walked into the studio with his guitar and a few lines of lyrics, hoping to sketch out a track or two just to stay busy, but that very first day he walked out with two finished songs and the inspiration to create something raw in real time, recording and releasing songs (and even videos!) direct to the public as soon as tape stopped rolling: “Everything was really as I did it,” he says.  “It was meant to be an experiment in how I could write and record and release something as quickly as possible. I didn’t wanna make an album—I wanted to put songs out every week. It’s personal for me.”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1483555998/event-7053500.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1395048',
    youTube: [ 'fYbJPcSbqe0', 'Xi7ObQDlW4Q' ],
    similarArtists:
     [ 'Black Pistol Fire',
       'The Stone Foxes',
       'Dan Auerbach',
       'Deap Vally',
       'The Pack A.D.' ] },
  { venue: 'The Chapel',
    title: [ 'The Frights', ' The Garden', ' The Regrettes', ' Dinosaurs' ],
    headliner: 'The Frights',
    date: '2017-02-25',
    startTime: '7:00',
    cost: 15,
    artistSummary: '’ birth in December 2012, was an accident that now unites moms worldwide. One mom in San Diego has called the band, “Great! A fun mix of the rock n’ roll I used to love with the 50’s sounds MY mom used to love!” Another mom in Los Angeles praises the band, saying, “I hire a babysitter to go to all their shows. They just have so much youthful energy, they make me feel young too!”',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479106906/event-6948117.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1383267',
    youTube: [ 'Qp8T-OjcUrI', '26d_4C3Lnr4' ],
    similarArtists:
     [ 'Swmrs',
       'Tijuana Panthers',
       'Bleeding Knees Club',
       'Vundabar',
       'The Babies' ] },
  { venue: 'The Chapel',
    title: [ 'Ceremony', ' Nothing', ' The World' ],
    headliner: 'Ceremony',
    date: '2017-02-26',
    startTime: '7:00',
    cost: 18,
    artistSummary: 'There are multiple artists with this name:\n\n1) Ceremony is a hardcore punk band from the San Francisco Bay Area that formed in 2005. \nhttp://www.ceremonyhc.com \n\n2) Ceremony is a Post-Punk/Shoegaze band from Fredericksburg, Virginia, featuring two members of Skywave. Their next release is slated to be released in Mid April. \n\n3) Ceremony is a rock band based in Australia with a worldwide release of their debut album available early 2008. \n\n4) Ceremony',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484169213/event-7250768.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1413604%2Ftfly',
    youTube: [ 'I4pFg3xoTYk', 'Pf6SHq7N8SA' ],
    similarArtists:
     [ 'Blacklisted',
       'Trash Talk',
       'Dangers',
       'Cold World',
       'Self Defense Family' ] },
  { venue: 'The Chapel',
    title: [ 'At the Mardi Gras with Zigaboo Modeliste' ],
    headliner: 'At the Mardi Gras with Zigaboo Modeliste',
    date: '2017-02-28',
    startTime: '7:00',
    cost: 20,
    artistSummary: 'Zigaboo Modeliste and the New Aahkesstra\nJoseph “Zigaboo” Modeliste is a master drummer, rhythm innovator, percussionist, and New Orleans legend. The most highly-acclaimed drummer ever to hail from the Crescent City, Ziggy’s creativity has been a wellspring of funk influence for three decades, inspiring many Hip-Hop tracks. His innovative work as a member of the internationally acclaimed R&B group, The Meters, as well as his side work with artists like Keith Richards, Robert Palmer and Dr. John, have garnered him an unparalleled level of respect among musicians and fans. Ziggy’s style is unique. He is a master of creating funk grooves and new concepts for funk drumming. Zigaboo’s music consistently demonstrates his brilliance as the premier funk drummer of the contemporary era. \nThe original The Meters LP’s were all recorded with Ziggy at the drums, and his work has been sampled many times over by artists such as Musiq, Queen Latifah, Run DMC, NWA, Ice Cube, Salt N’ Pepa, Cypress Hill, EPMD, Public Enemy, A Tribe Called Quest, Beastie Boys, Naughty by Nature, and Tweet, just to name a few. Ziggy is a BMI award winner for the Young Gunz track, “Can’t Stop Won’t Stop.” His drum sound also provided the main loops for Amerie’s “1Thing,” which was nominated for two Grammy’s and was #1 on the R&B charts. \nZiggy has written over 200 songs individually and collectively with The Meters. His songwriting displays both his musical genius and original funk style. Zigaboo’s songs have been released on over 56 albums nationally and internationally. His tunes have also graced such movies as “Two Can Play That Game,” “Jackie Brown,” “Drum Line,” “8 Mile,” “Hancock,” “Red,” and a Nike Commercial for Footaction. Zig was featured in producer Mark Ronson’s 2011 Re:Generation Music Project, where he wrote and performed the original song “A La Modeliste,” with Erykah Badu, Mos Def, Trombone Shorty, and members of The Dap Kings. Zigaboo’s latest 2011 release, “New Life,” was praised as an amazing slide of funk—proof that Modeliste’s fountain of rhythmic imagination shows no signs of running dry. Ziggy’s first solo CD, “Zigaboo.com”, was released in 2000 and was reviewed as one of the most outstanding comeback records of the year. In 2004, the follow-up CD, “I’m on the Right Track,” featured special guests, Dr. John and Bernie Worrell. “Funk Me Hard Live” is a collection of funk originals recorded in 1980 and released in 2009. All these ever-grooving solo iconic albums were released on Zigaboo’s own label, JZM Records and are available for download from iTunes and on CD at Zigaboo.com and CDBaby.com. In 2013, Drum Channel and Zigaboo Modeliste released a DVD, ”The Originator of New Orleans Funky Drumming”—a history/biography of Zigaboo’s New Orleans Style Drumming approach and technique. Zig was honored with the cover story in the August, 2013, edition of Modern Drummer. He is also featured as he holds down the groove at Bonnaroo 2013 in the star-studded “Rock and Soul Dance Party,” singing his song, “Hey Pocky Away,” available on YouTube. \nIn 2014, Zigaboo’s drum work was sampled in Eminem’s award ( A Billboard # 1 BMI Award) winning single, “Berserk”, later that year Zigaboo along with his work with the Meters was showcased in Dave Grohl’s and HBO’s docuseries, “Sonic Highways”. \nOther accolades include being named one of the “Top 100 most Influential Drummers Ever” by Total Drumsets, Zigaboo’s legacy has also been immortalized in songs such as, “Ziggowatt” by Lettuce and “Zigaboogaloo” by Nicholas Payton. \nThe King of the Funky Drums, Percussion Maestro, and Godfather of Groove, Zigaboo Modeliste takes listeners to funk depths only he could possibly reach!',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484169394/event-7177161.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1407545%2Ftfly',
    youTube: [ 'Wz4hJZhHd88', 'KKn25GwXa24' ],
    similarArtists: [] },
  { venue: 'The Chapel',
    title: [ 'Bell X1', ' Vita and The Woolf' ],
    headliner: 'Bell X1',
    date: '2017-03-01',
    startTime: '8:00',
    cost: 20,
    artistSummary: 'Fellow Irish rockers U2 seemed to have had a bit of luck naming themselves after a spy plane, so it makes since that  adopted the name of the plane Chuck Yaeger used to break the sound barrier in 1947. Further comparisons to U2 just seem lazy, though fans of Coldplay and even the Talking Heads (courtesy of signer Paul Noonan’s occasionally very David Byrne-esque delivery) will find much to love about Bell X1’s unerringly melodic, bittersweet pop tunes.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1479341717/event-6970924.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1385118%2Ftfly',
    youTube: [ 'q_SoCCIVCwc', 'gGj0xuVceaw' ],
    similarArtists:
     [ 'The Frames',
       'Mic Christopher',
       'Mundy',
       'Ham Sandwich',
       'Paddy Casey' ] },
  { venue: 'The Chapel',
    title: [ 'The Killer Queens', ' Neon Velvet' ],
    headliner: 'The Killer Queens',
    date: '2017-03-04',
    startTime: '8:00',
    cost: 18,
    artistSummary: 'The Killer Queens are a high energy all girl tribute to Queen that focuses on the live show as originally portrayed by Queen. Equipped with Brian May\'s Red Special and Vox amp, Freddie Mercury\'s free falling mic stand and authentic costumes to match, they offer a full show with costume changes, lights, fog and a professionalism for all ages to enjoy.',
    photo: 'https://res.cloudinary.com/dostuff-media/image/upload//c_fill,g_faces,b_rgb:090909,q_60,fl_lossy,w_1200,h_450/v1484169814/event-7080641.jpg',
    link: 'http://www.shareasale.com/r.cfm?u=1098158&b=234786&m=27601&afftrack=&urllink=https%3A%2F%2Fwww.ticketfly.com%2Fpurchase%2Fevent%2F1398167%2Ftfly',
    youTube: [ '2ZBtPf7FOoM', 'bFqHUI4b_is' ],
    similarArtists: [] } ]

module.exports = shows;
