// const shows = [ { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/Wintersleep-Photo-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, November 19, 2016',
//     title: 'Fake Palms',
//     cost: '25',
//     startTime: '9:30',
//     youTube: [ 'jkgDvLA4kYw', '5u_vXkQg0OI' ],
//     similarArtists:
//      [ 'Greys',
//        'Corsica Arts Club',
//        'Mike Krol',
//        'HSY',
//        'White Reaper' ],
//     artistSummary: 'Fake Palms are a Toronto-based band signed to Buzz Records' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/ATribeCalledRed_TM_2426x1365_photo_only-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Monday, November 21, 2016',
//     title: 'OKA',
//     cost: '25',
//     startTime: '9:30',
//     youTube: [ 'pywCWGGmOxM', undefined ],
//     similarArtists:
//      [ 'Jen Meets Salz',
//        'Audio Shaman',
//        'Razoof',
//        'Clélia FELIX',
//        'The Red Eyes' ],
//     artistSummary: 'There is more than one artist with this name:\n\n1) Nyoman Oka Antara (born 8 July 1981) is an Indonesian rapper and actor of Balinese descent.\n2) Oka, a band from the Sunshine Coast north of Brisbane, Australia.  \n3) OKA is also a pop group from Finland.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/GordBamford_IG_1080x1080_Vancouver600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Tuesday, November 22, 2016',
//     title: 'Meghan Patrick',
//     youTube: [ 'rvNw-Ry8wjY', 'mqIbcMQV6rU' ],
//     similarArtists:
//      [ 'Madeline Merlo',
//        'Cold Creek County',
//        'Lindsay Ell',
//        'Autumn Hill',
//        'Tebey' ],
//     artistSummary: 'Born and raised in Bowmanville, Ontario, Meghan Patrick has dedicated her entire life to music, wanting it to be more than just a passion. “I was drawn to playing guitar so I could start writing music to go along with the words I was writing. I wanted to be self-sufficient as a creative artist.”  It wasn’t long until Meghan had mastered both electric and acoustic guitar as well as the banjo.\n\nPrior to setting out as a solo artist, Meghan was the lead singer of the popular roots act The Stone Sparrows.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, November 23, 2016',
//     title: 'Adam Baldwin',
//     cost: '25',
//     startTime: '9:30',
//     youTube: [ 'ynKKAwXhfXM', 'YALS1sMzpwM' ],
//     similarArtists:
//      [ 'Firefly music project',
//        'Sheena Harden',
//        'Sharon Bee',
//        'Nathan Town',
//        'Jed Whedon' ],
//     artistSummary: 'Adam has just been added to the Toronto Urban Roots Festival line up! Adam \nand his band will open for The Sheepdogs at Lee\'s Palace on Sept 14 as part of ...' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/JamesVincentMcMorrow_Commodore-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, November 24, 2016',
//     title: 'Allan Rayman',
//     cost: '32',
//     startTime: '9:00',
//     youTube: [ undefined, 'xGKIcgwlPPc' ],
//     similarArtists:
//      [ 'Johnny Rain',
//        'RKCB',
//        'Lawrence Taylor',
//        'Francesco Yates',
//        'Jahkoy' ],
//     artistSummary: '..' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, November 25, 2016',
//     title: 'Adam Baldwin',
//     cost: '25',
//     startTime: '9:30',
//     youTube: [ 'ynKKAwXhfXM', 'YALS1sMzpwM' ],
//     similarArtists:
//      [ 'Firefly music project',
//        'Sheena Harden',
//        'Sharon Bee',
//        'Nathan Town',
//        'Jed Whedon' ],
//     artistSummary: 'Adam has just been added to the Toronto Urban Roots Festival line up! Adam \nand his band will open for The Sheepdogs at Lee\'s Palace on Sept 14 as part of ...' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Tuesday, November 29, 2016',
//     title: 'Lucie Silvas',
//     cost: '32',
//     startTime: '9:30',
//     youTube: [ 'GlazjTgLN2M', 'byAGy_mFIdg' ],
//     similarArtists:
//      [ 'Delta Goodrem',
//        'Nerina Pallot',
//        'Amy Studt',
//        'Sandi Thom',
//        'Tina Arena' ],
//     artistSummary: ' Lucie Silvas born 4 September 1977 in Kingston-Upon-Thames, London is a singer/songwriter from the United Kingdom. \n\nBorn Lucie Joanne Silverman. Lucie left school in the sixth form, where she became a backing vocalist for ex-Take That vocalist Gary Barlow and singer Judie Tzuke. In 2000 Lucie Silvas recorded her album "Forget Me Not" - with tracks including the single "It\'s Too Late". This song entered the charts with a low position, and Lucie was subsequently dropped from her record label.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, November 30, 2016',
//     title: 'Lucie Silvas',
//     cost: '32',
//     startTime: '9:30',
//     youTube: [ 'GlazjTgLN2M', 'byAGy_mFIdg' ],
//     similarArtists:
//      [ 'Delta Goodrem',
//        'Nerina Pallot',
//        'Amy Studt',
//        'Sandi Thom',
//        'Tina Arena' ],
//     artistSummary: ' Lucie Silvas born 4 September 1977 in Kingston-Upon-Thames, London is a singer/songwriter from the United Kingdom. \n\nBorn Lucie Joanne Silverman. Lucie left school in the sixth form, where she became a backing vocalist for ex-Take That vocalist Gary Barlow and singer Judie Tzuke. In 2000 Lucie Silvas recorded her album "Forget Me Not" - with tracks including the single "It\'s Too Late". This song entered the charts with a low position, and Lucie was subsequently dropped from her record label.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/tdw_2016-scene-02_Scott_green-24-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Tuesday, December 6, 2016',
//     title: 'Telegram',
//     cost: '32',
//     startTime: '8:00',
//     youTube: [ 'dloCmKoQoEA', 'ro9slbz0XJs' ],
//     similarArtists:
//      [ 'Sunflower Bean',
//        'Mystery Jets',
//        'Hooton Tennis Club',
//        'Blossoms',
//        'Eagulls' ],
//     artistSummary: 'Telegram are a London based band formed in 2013. The band consists of Welsh frontman Matt Saunders, Matt Wood on guitar, Oli Paget-Moon on bass and Jordan Cook on drums. Influenced by their love of Eno, Syd Barrett, krautrock and late proto-punk, Telegram released their debut single "Follow" (B-side "Under The Night Time") on their own GramGram label in November 2013. \n\nTelegram have supported Franz Ferdinand, Manic Street Preachers and Temples in the past and are about to join Palma Violets on their upcoming tour in November. ' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Michael-Kiwanuka-Approved-Photo600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, December 7, 2016',
//     title: 'Cloves',
//     cost: '25',
//     startTime: '8:00',
//     youTube: [ 'F_Jk_uQ4gSg', '82CdBc0-Umw' ],
//     similarArtists: [ 'Ofelia K', 'TransViolet', 'RKCB', 'kiiara', 'KIll J' ],
//     artistSummary: 'http://cloves.bandcamp.com' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/06/AD-comm-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Monday, December 12, 2016',
//     title: 'Chloe X Halle',
//     cost: '30',
//     startTime: '8:15',
//     youTube: [ undefined, 'dvowOF4qrjQ' ],
//     similarArtists: [ 'Solange', 'Beyoncé', 'Destiny\'s Child', 'Tinashe', 'Fantasia' ],
//     artistSummary: 'Chloe and Halle Bailey (born July 1, 1998 and March 27, 2000 respectively) are American sisters, YouTube sensations, singers and actresses. Both born in Atlanta GA, they later moved to Los Angeles with their family to pursue music careers. In 2013, after their cover for "Pretty Hurts" went viral with nearly 12 million views, Beyoncé signed them to her management Parkwood Entertainment.[1] They were amongst the three talents she signed, others being Sophie Beem and Ingrid.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/InFlamesForgedinFireTour-approvedimage_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, December 14, 2016',
//     title: 'HELLYEAH',
//     cost: '42',
//     startTime: '8:00',
//     youTube: [ 'SBaIQreV8Yk', 'Y_nZfjZVaEg' ],
//     similarArtists:
//      [ 'Texas Hippie Coalition',
//        'Damageplan',
//        'DevilDriver',
//        'Rebel Meets Rebel',
//        'Five Finger Death Punch' ],
//     artistSummary: 'Hellyeah is a rock band which formed in Dallas, Texas, United States in 2006. The band consists of Chad Grey (vocals), Greg Tribbett (guitar), Tom Maxwell (guitar), Bob Zilla (bass) and Vinnie Paul Abbott (drums). Grey and Tribbet are members of Mudvayne, Maxwell is a member of Nothingface, Zilla was a member of Damageplan and Abbott was a member of Pantera and Damageplan. The band has released two albums, "Hellyeah" (2007) and "Stampede" (2009).' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, December 21, 2016',
//     title: 'Russ Liquid',
//     cost: '30',
//     startTime: '9:30',
//     youTube: [ 'yiJne9h5G4c', '8DF1qQtzexc' ],
//     similarArtists:
//      [ 'Freddy Todd',
//        'Gladkill',
//        'Thriftworks',
//        'MartyParty',
//        'Vibesquad' ],
//     artistSummary: 'Set apart from other up-and-coming West Coast bass music producers by his extensive world-touring history and performance experience, Russ Liquid brings a much-needed injection of melody and emotion to the thriving dance floor community. Classically trained on the piano, trumpet, saxophone and flute, Russ Liquid applies the colorful tones of instrumental music to the realm of beats with dance floor-rocking results. This talented producer has found an entirely new palette to “paint” with' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, December 22, 2016',
//     title: 'Russ Liquid',
//     cost: '30',
//     startTime: '9:30',
//     youTube: [ 'yiJne9h5G4c', '8DF1qQtzexc' ],
//     similarArtists:
//      [ 'Freddy Todd',
//        'Gladkill',
//        'Thriftworks',
//        'MartyParty',
//        'Vibesquad' ],
//     artistSummary: 'Set apart from other up-and-coming West Coast bass music producers by his extensive world-touring history and performance experience, Russ Liquid brings a much-needed injection of melody and emotion to the thriving dance floor community. Classically trained on the piano, trumpet, saxophone and flute, Russ Liquid applies the colorful tones of instrumental music to the realm of beats with dance floor-rocking results. This talented producer has found an entirely new palette to “paint” with' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2014/11/Commodore-Thumbnail-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, December 31, 2016',
//     title: 'SJS NYE 2017',
//     cost: '40',
//     startTime: '9:00',
//     youTube: [ undefined ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, January 7, 2017',
//     title: 'Jojo Mason',
//     cost: '40',
//     startTime: '9:00',
//     youTube: [ 'u9z1yszloAE', 'OBKAisQOraI' ],
//     similarArtists:
//      [ 'PETRIC',
//        'The Washboard Union',
//        'James Barker Band',
//        'River Town Saints',
//        'Dan Davidson' ],
//     artistSummary: 'Made For You - Single, Jojo Mason' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Sunday, January 8, 2017',
//     title: 'Jojo Mason',
//     cost: '40',
//     startTime: '9:00',
//     youTube: [ 'u9z1yszloAE', 'OBKAisQOraI' ],
//     similarArtists:
//      [ 'PETRIC',
//        'The Washboard Union',
//        'James Barker Band',
//        'River Town Saints',
//        'Dan Davidson' ],
//     artistSummary: 'Made For You - Single, Jojo Mason' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/BallroomBrawl7_600x500_Vancouver-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, January 14, 2017',
//     title: 'ECCW Ballroom Brawl VII',
//     cost: '20',
//     startTime: '8:00',
//     youTube: [ '_7X83_6Iyck', 'Q7xcnpc8bZ0' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/TheFighterAndTheKid_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, January 19, 2017',
//     title: 'The Fighter and the Kid',
//     cost: '25',
//     startTime: '9:00',
//     youTube: [ 'OdubY9b1Ud0', '-EojydAXveQ' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, January 20, 2017',
//     title: 'Steel Panther',
//     cost: '35',
//     startTime: '9:00',
//     youTube: [ 'G_vde4Ii8Ik', 'XXuN41avVRs' ],
//     similarArtists: [ 'Mötley Crüe', 'Reckless Love', 'Warrant', 'Poison', 'Ratt' ],
//     artistSummary: 'In 2008, Metal Skool changed their name to Steel Panther.\n\nSteel Panther is a Los Angeles, California based glam metal parody band founded by former LA Guns vocalist   Ralph Saenz  (Michael Starr). Originally formed as "Metal Skool" and "Metal Shop" they\'re known for their energetic live show, the longest running metal show on the Sunset Strip. On stage, the band both pays tribute to and lampoons the heyday of 80\'s glam metal. The band\'s between-song comedy includes jests at conflict between band members' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, January 21, 2017',
//     title: 'Steel Panther',
//     cost: '35',
//     startTime: '9:00',
//     youTube: [ 'G_vde4Ii8Ik', 'XXuN41avVRs' ],
//     similarArtists: [ 'Mötley Crüe', 'Reckless Love', 'Warrant', 'Poison', 'Ratt' ],
//     artistSummary: 'In 2008, Metal Skool changed their name to Steel Panther.\n\nSteel Panther is a Los Angeles, California based glam metal parody band founded by former LA Guns vocalist   Ralph Saenz  (Michael Starr). Originally formed as "Metal Skool" and "Metal Shop" they\'re known for their energetic live show, the longest running metal show on the Sunset Strip. On stage, the band both pays tribute to and lampoons the heyday of 80\'s glam metal. The band\'s between-song comedy includes jests at conflict between band members' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Sting600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, February 1, 2017',
//     title: 'Joe Sumner',
//     cost: '15',
//     startTime: '8:00',
//     youTube: [ '2IMnwxWABQQ', 'QmW0cWNP8Eo' ],
//     similarArtists: [],
//     artistSummary: 'Joseph Sumner (born 23 November 1976) is the son of actress Frances Tomelty and singer/actor/activist Gordon Sumner (known as Sting). He is the lead singer and bass player in the UK band Fiction Plane.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Sonreal-promo-photo_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, February 3, 2017',
//     title: 'SonReal',
//     cost: '20',
//     startTime: '9:30',
//     youTube: [ 'FyfjGuji3Wg', '_PyEkbj3UfA' ],
//     similarArtists:
//      [ 'Chris Webby',
//        'SonReal & Rich Kidd',
//        'Classified',
//        'Kardinal Offishall',
//        'OCD: Moosh & Twist' ],
//     artistSummary: 'SonReal is a young and independent artist from Vancouver, B.C. Canada. With his humbling attitude and social awareness, SonReal brings a distinctive quality to the Hip-Hop genre. His mature self-understanding compels him to create a unique perspective contrary to the stereo-typical urban artist. His lyrics reflect real life issues, addressing topics such as poverty, education and social acceptance. Live instrumentals combined with natural vocal talent provide harmony and set SonReal apart from the average rapper.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/RBF600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, February 9, 2017',
//     title: 'Ballyhoo!',
//     cost: '27',
//     startTime: '8:00',
//     youTube: [],
//     similarArtists:
//      [ 'Passafire',
//        'One Drop',
//        'The Expendables',
//        'Pepper',
//        'Three Legged Fox' ],
//     artistSummary: 'There are, at least, two groups by this name. Ballyhoo (without the exclamation mark!) is a South African group who had a huge hit in 1980 in their homeland with their single \'Man On The Moon\'. This South African group is still going strong. The other group with the same name (but with the exclamation mark!) is from Maryland, USA, a modern rock/reggae party band, active since 2006.\n\nBALLYHOO! is undeniably turning the world of music upside down and sideways as they blur the lines between rock' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/USS-image-600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, February 10, 2017',
//     title: 'Repartee',
//     cost: '30',
//     startTime: '9:00',
//     youTube: [ 'ogzR6EhHiYQ', '7Ff9wmilVos' ],
//     similarArtists:
//      [ 'Matthew Hornell and The Diamond Minds',
//        'Andrew James O\'Brien',
//        'Motel Raphaël',
//        'Jane\'s Party',
//        'Beach Tiger' ],
//     artistSummary: 'Repartee’s music has been described as ‘the kind of music that allows you to let loose while dancing, without giving a f*** about how foolish you look’ (the Muse). They play keyboard-based pop with elements of gritty rock. In a short period of time they’ve commanded a devoted following in St. John’s through their dynamic live show. It’s that sort of buzz that led to them receiving a MusicNL Professional Demo Grant to make their first EP, ‘Lost Like We All Are’.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, February 16, 2017',
//     title: 'Craig Stickland',
//     cost: '42',
//     startTime: '9:00',
//     youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
//     similarArtists:
//      [ 'Josh Auer',
//        'Bryce Jardine',
//        'Mark Diamond',
//        'Rebecca Roubion',
//        'Taylor  Mathews' ],
//     artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, February 17, 2017',
//     title: 'Craig Stickland',
//     cost: '42',
//     startTime: '9:00',
//     youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
//     similarArtists:
//      [ 'Josh Auer',
//        'Bryce Jardine',
//        'Mark Diamond',
//        'Rebecca Roubion',
//        'Taylor  Mathews' ],
//     artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, February 18, 2017',
//     title: 'Craig Stickland',
//     cost: '42',
//     startTime: '9:00',
//     youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
//     similarArtists:
//      [ 'Josh Auer',
//        'Bryce Jardine',
//        'Mark Diamond',
//        'Rebecca Roubion',
//        'Taylor  Mathews' ],
//     artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/cadillacthreeTM-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, March 8, 2017',
//     title: 'The Cadillac Three',
//     cost: '27',
//     startTime: '9:30',
//     youTube: [ 'KLLp7jbQaYY', 'yb7iP-A6NHI' ],
//     similarArtists:
//      [ 'Blackberry Smoke',
//        'Whiskey Myers',
//        'Blackfoot',
//        'Black Stone Cherry',
//        'Monster Truck' ],
//     artistSummary: 'The Cadillac Three, originally known as Cadillac Black, is an American country music group consisting of Jaren Johnston (lead vocals, guitar), Kelby Ray (bass guitar, Dobro, acoustic guitar, vocals), and Neil Mason (drums, vocals).' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Blackie-and-the-Rodeo-Kings-600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, March 10, 2017',
//     title: 'An Evening with Blackie and The Rodeo Kings',
//     cost: '45',
//     startTime: '9:00',
//     youTube: [ 'FaVjFNJIxfU', 'acJhHs8HsRs' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Japandroids305x225-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Monday, March 20, 2017',
//     title: 'Craig Finn',
//     cost: '25',
//     startTime: '9:30',
//     youTube: [ 'JaUJnPWeBKc', '1brqbaX5xiI' ],
//     similarArtists:
//      [ 'The Hold Steady',
//        'Jason Isbell',
//        'Cory Branan',
//        'Josh Ritter',
//        'Dave Hause' ],
//     artistSummary: 'Craig Finn is the man behind Lifter Puller, The Brokerdealer and The Hold Steady.  He was also featured on Rhymesayers rapper P.O.S.\'s Safety In Speed (Heavy Metal).  He released his first solo album,  Clear Heart Full Eyes, on January of 2012.\n\nHere is some background information on Clear Heart Full Eyes from the  No Future Songfacts . In early 2011 Hold Steady frontman Craig Finn challenged himself to write a new song every day in his Brooklyn apartment for his first solo album.' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, March 31, 2017',
//     title: 'The Tea Party #TX20',
//     cost: '39',
//     startTime: '9:30',
//     youTube: [ undefined, 'YfaATa-qmG4' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, April 1, 2017',
//     title: 'The Tea Party #TX20',
//     cost: '39',
//     startTime: '9:30',
//     youTube: [ undefined, 'YfaATa-qmG4' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/The-Damned-600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Saturday, April 15, 2017',
//     title: 'The Damned: 40th Anniversary U.S. Tour',
//     cost: '29',
//     startTime: '9:00',
//     youTube: [ 'w1wbX3mICqw', 'cqCbdLXkLTI' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Zombies_Image_600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Friday, April 21, 2017',
//     title: 'The Zombies: Odessey & Oracle 50th Anniversary',
//     cost: '45',
//     startTime: '9:00',
//     youTube: [ 'goDxhJl1UJE', 'AL6K-acL2BU' ],
//     similarArtists: [] },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/bonobo305-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Wednesday, May 24, 2017',
//     title: 'Bonobo',
//     cost: '35',
//     startTime: '8:00',
//     youTube: [ 'tUzY3zc9vs8', 'fQAFfeQNpGc' ],
//     similarArtists:
//      [ 'Emancipator',
//        'Blockhead',
//        'Thievery Corporation',
//        'The Cinematic Orchestra',
//        'Mechanical Me' ],
//     artistSummary: 'Simon Green AKA Bonobo\'s first album - 2000\'s \'Animal Magic\' - was released via Tru Thoughts before being picked up by Ninja Tune. It announced him as a serious talent; able to bring a musician\'s edge to electronic music, with all the freedom that skill allowed. His subsequent albums for Ninja, Dial M for Monkey and Days to Come, developed his sensibility, won him fans across the globe, and saw him develop his live show into a mesmeric re-working of his records. ' },
//   { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/bonobo600x500-230x170.jpg',
//     link: 'http://www.commodoreballroom.com/calendar/',
//     venue: 'Commodore Ballroom',
//     date: 'Thursday, May 25, 2017',
//     title: 'Bonobo',
//     cost: '35',
//     startTime: '8:00',
//     youTube: [ 'tUzY3zc9vs8', 'fQAFfeQNpGc' ],
//     similarArtists:
//      [ 'Emancipator',
//        'Blockhead',
//        'Thievery Corporation',
//        'The Cinematic Orchestra',
//        'Mechanical Me' ],
//     artistSummary: 'Simon Green AKA Bonobo\'s first album - 2000\'s \'Animal Magic\' - was released via Tru Thoughts before being picked up by Ninja Tune. It announced him as a serious talent; able to bring a musician\'s edge to electronic music, with all the freedom that skill allowed. His subsequent albums for Ninja, Dial M for Monkey and Days to Come, developed his sensibility, won him fans across the globe, and saw him develop his live show into a mesmeric re-working of his records. ' },
//   { date: 'Tuesday November 22nd ',
//     title: 'Mr Little Jeans',
//     cost: '18',
//     startTime: '7',
//     link: 'http://biltmorecabaret.com/events/mr-little-jeans/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/MrLittleJeansPoster-663x1024.jpg',
//     fb: 'https://www.facebook.com/events/174735252965763/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ '90CGCzBs3gQ', 'oB13wqesv_g' ],
//     similarArtists: [],
//     artistSummary: 'Mr. Little Jeans, a singer deep deep from the Norwegian woods, currently based between Stockholm & LA' },
//   { date: 'Thursday November 24th ',
//     title: 'Van Damsel',
//     cost: '12',
//     startTime: '7',
//     link: 'http://biltmorecabaret.com/events/van-damsel/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/VanDamselPoster-663x1024.jpg',
//     fb: 'https://www.facebook.com/events/1289733651066291/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'A-YHP3rf5Js', 'gbdleQUSUfc' ],
//     similarArtists:
//      [ 'Sun Culture',
//        'Fine Times',
//        'Kiki Rowe',
//        'Black Black Hills',
//        'Head Of The Herd' ],
//     artistSummary: 'Van Damsel is a guitar-driven indie-rock act with a modern edge, combining an upbeat, danceable, and hard-hitting sound with ambient, emotional textures and highly relatable lyrics.' },
//   { date: 'Friday November 25th ',
//     title: 'TUNS',
//     cost: '15',
//     startTime: '7',
//     link: 'http://biltmorecabaret.com/events/tuns/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/TunsPoster-663x1024.jpg',
//     fb: 'https://www.facebook.com/events/561440730724093/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'ZG3JXEJLXnM', 'euhknTzBe8o' ],
//     similarArtists:
//      [ 'The Damn Truth',
//        'Only Yours',
//        'Your Boy Tony Braxton',
//        'The StandStills',
//        'Dawg Yawp' ],
//     artistSummary: 'Top Hits Who cares about the chart order, less rap & more hits! 80s Hits Hear \nyour classic favorites right here! Soft Rock The best in Soft Rock music!' },
//   { date: 'Saturday November 26th ',
//     title: 'Paper Lions',
//     cost: '14',
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/paper-lions/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/PaperLionsPoster-663x1024.jpg',
//     fb: 'https://www.facebook.com/events/1773006039612600/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'etCGZos14S4', 'Q1sHvKfKFZs' ],
//     similarArtists:
//      [ 'Said the Whale',
//        'Two Hours Traffic',
//        'Hey Rosetta!',
//        'The Zolas',
//        'Arkells' ],
//     artistSummary: '(1)  Hailing from the unlikely small community of Belfast, Prince Edward Island, brothers John and Rob MacPhee and neighbour Colin Buchanan began playing music together at a very young age in a variety of garage bands. After meeting in high school, David Cyrus MacDonald was recruited and Paper Lions cemented with John and Rob filling the positions of lead vocals and bass respectively, Colin on lead guitar and David on drums. \n\nAfter the release of their critically acclaimed' },
//   { date: 'Sunday November 27th ',
//     title: 'Kitty Nights\' Fall Burlesque Showcase!',
//     cost: '10',
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/kitty-nights-fall-burlesque-showcase/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14494661_1217017791702679_6483826289690522254_n.jpg',
//     fb: 'https://www.facebook.com/events/107631692996243/',
//     venue: 'Biltmore Cabaret',
//     youTube: [],
//     similarArtists: [] },
//   { date: 'Wednesday November 30th ',
//     title: 'CRX',
//     cost: '15',
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/crx/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14484607_10154703345994255_2481276756092808628_n.jpg',
//     fb: 'https://www.facebook.com/events/998397083603040/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'yquKa6GJ8i8', 'KsXYnhNXUb8' ],
//     similarArtists:
//      [ 'The Strokes',
//        'Vant',
//        'Beware of Darkness',
//        'Deap Vally',
//        'The Kills' ],
//     artistSummary: 'The Strokes\' Nick Valensi project, CRX other members are Ralph Alexander (The Dose), Richie Follin (Guards), Darian Zahedi, and Jon Safley (The Reflections).' },
//   { date: 'Tuesday December 6th ',
//     title: 'Wild Child',
//     cost: '49',
//     startTime: 'Not Available',
//     link: 'http://biltmorecabaret.com/events/wild-child/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/WILD-CHILD-APPROVED-PHOTO-1-1024x689.jpg',
//     fb: 'https://www.facebook.com/events/1143044845716045/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ '878_AiEkU4s', 'n-qpJ0owFcc' ],
//     similarArtists:
//      [ 'Phox',
//        'The Oh Hellos',
//        'The Lighthouse and the Whaler',
//        'Blind Pilot',
//        'Hey Marseilles' ],
//     artistSummary: 'There are 4 active bands using the name Wild Child.\n\n1. A six-piece indie folk band from Austin, TX. \nMembers are: primary singers/songwriters Kelsey Wilson and Alexander Beggins, drummer Carey McGraw, cellist Sadie Wolfe, keyboardist Evan Magers and bassist Chris D\'Annunzio They are managed by Pat Cassidy.\nTheir first album, the 15-track Pillow Talk, was released on October 25, 2011 with help from San Francisco producers Evan Magers and Alex Peterson, and mastered by Erik Wofford).' },
//   { date: 'Saturday December 10th ',
//     title: 'Mia Stammer + Adelaine Morin: Vancouver',
//     cost: '15',
//     startTime: '30',
//     link: 'http://biltmorecabaret.com/events/mia-stammer-adelaine-morin-vancouver/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Mia-1024x1024.jpg',
//     fb: 'https://www.facebook.com/events/158033394656968/',
//     venue: 'Biltmore Cabaret',
//     youTube: [],
//     similarArtists: [] },
//   { date: 'Saturday December 17th ',
//     title: 'COASTLINE PILOT',
//     cost: '18',
//     startTime: '7',
//     link: 'http://biltmorecabaret.com/events/coastline-pilot/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/coastlinevaultryjaketouzelinsta-1024x1024.jpg',
//     fb: 'https://www.facebook.com/events/189497901509330/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'mJDkCcwAQEk', '21lwh4GR1Qk' ],
//     similarArtists: [],
//     artistSummary: 'Coastline Pilot ..' },
//   { date: 'Monday January 16th ',
//     title: 'John Paul White',
//     cost: '18',
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/john-paul-white/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/John-Paul-White-Approved-Photo-1-1024x768.jpg',
//     fb: 'https://www.facebook.com/events/1792909857638054/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'GpzSViue1SM', undefined ],
//     similarArtists:
//      [ 'Lera Lynn',
//        'The Civil Wars',
//        'Lori McKenna',
//        'Alexandra Savior',
//        'Aoife O\'Donovan' ],
//     artistSummary: 'From deep in inland Alabama comes a talent so effortless and sincere that it is a wonder why the big wigs didn\'t jump on him sooner. John Paul White, who has recently signed with mega-label Capitol Records, relies mostly on his acoustic guitar to build his songs - but has no problems dressing them up with melodic electric guitar lines. I know I\'m always pulling the dramatics out of my hat, but these songs really are achingly beautiful. I hope you\'ll hear more from JPW in the future as he records his new disc for Capitol.' },
//   { date: 'Thursday February 2nd ',
//     title: 'Lydia Loveless',
//     cost: '20',
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/lydia-loveless/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/15003365_1011783955610301_6933406659675946928_o-683x1024.jpg',
//     fb: 'http://biltmorecabaret.com/concerts/facebook.com/events/1775334666051468/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ '3XyKhTwk9X8', 'YPk2I475zOY' ],
//     similarArtists:
//      [ 'Nikki Lane',
//        'Amanda Shires',
//        'John Moreland',
//        'Drive-By Truckers',
//        'Robbie Fulks' ],
//     artistSummary: 'Blessed with a commanding, blast-it-to-the-back-of-the room voice, the 24-year-old Lydia Loveless was raised on a family farm in Coshocton, Ohio, US—a small weird town with nothing to do but make music. With a dad who owned a country music bar, Loveless often woke up with a house full of touring musicians scattered on couches and floors.\n\nWhen she got older, in the time-honored traditions of teenage rebellion, she turned her back on these roots' },
//   { date: 'Thursday February 16th ',
//     title: 'CLOUD NOTHINGS',
//     cost: undefined,
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/cloud-nothings/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/CloudNothings2017_PressPhoto-1024x1024.jpg',
//     fb: 'https://www.facebook.com/pg/biltmorecabaret/events/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'rt9N_yHvwyM', 'uaCIWOWUWww' ],
//     similarArtists:
//      [ 'Japandroids',
//        'Wavves',
//        'Wavves X Cloud Nothings',
//        'Cymbals Eat Guitars',
//        'Yuck' ],
//     artistSummary: 'Cloud Nothings is an indie rock band from Cleveland, Ohio. Dylan Baldi started Cloud Nothings as a way to amuse himself between classes at Case Western Reserve University in 2009. The first batch of Cloud Nothings songs, including the blogosphere favorite "Hey Cool Kid" (available on the 2010 compilation "Turning On"), was recorded on a computer in the basement of Baldi\'s home in Westlake, OH. A concert promoter who invited Cloud Nothings to play' },
//   { date: 'Wednesday February 22nd ',
//     title: 'clipping',
//     cost: undefined,
//     startTime: '8',
//     link: 'http://biltmorecabaret.com/events/clipping/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Tennis_Press-1024x728.jpg',
//     fb: 'https://www.facebook.com/events/1780034532213944/',
//     venue: 'Biltmore Cabaret',
//     youTube: [ '_nibVU1RjAM', 'B6Xt5K66dHk' ],
//     similarArtists: [],
//     artistSummary: 'There are several artist named "clipping".\n\nFor the LA rap trio, please see clipping.' },
//   { date: 'Wednesday March 1st ',
//     title: 'Tennis with guests',
//     cost: undefined,
//     startTime: undefined,
//     link: 'http://biltmorecabaret.com/events/tennis-with-guests/',
//     photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Joseph_credit_Ebru_Yildiz-1024x579.jpg',
//     fb: 'https://www.facebook.com/events/1104129646368219/?notif_t=plan_admin_added&notif_id=1478016004034011#',
//     venue: 'Biltmore Cabaret',
//     youTube: [ 'Px9biv1pgVE', 'RWJoaWQmraM' ],
//     similarArtists: [] } ]
//
//     export default shows;


const shows = [ { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/ATribeCalledRed_TM_2426x1365_photo_only-230x170.jpg',
    link: 'http://www.commodoreballroom.com/calendar/',
    venue: 'Commodore Ballroom',
    date: 'Monday, November 21, 2016',
    title: 'OKA',
    cost: '25',
    startTime: '9:30',
    youTube: [ 'pywCWGGmOxM', 'D2koULTEfBs' ],
    similarArtists:
     [ 'Jen Meets Salz',
       'Audio Shaman',
       'Razoof',
       'Clélia FELIX',
       'The Red Eyes' ],
    artistSummary: 'There is more than one artist with this name:\n\n1) Nyoman Oka Antara (born 8 July 1981) is an Indonesian rapper and actor of Balinese descent.\n2) Oka, a band from the Sunshine Coast north of Brisbane, Australia.  \n3) OKA is also a pop group from Finland.' }]
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/GordBamford_IG_1080x1080_Vancouver600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, November 22, 2016',
  //   title: 'Meghan Patrick',
  //   youTube: [ 'rvNw-Ry8wjY', 'mqIbcMQV6rU' ],
  //   similarArtists:
  //    [ 'Madeline Merlo',
  //      'Cold Creek County',
  //      'Lindsay Ell',
  //      'Autumn Hill',
  //      'Tebey' ],
  //   artistSummary: 'Born and raised in Bowmanville, Ontario, Meghan Patrick has dedicated her entire life to music, wanting it to be more than just a passion. “I was drawn to playing guitar so I could start writing music to go along with the words I was writing. I wanted to be self-sufficient as a creative artist.”  It wasn’t long until Meghan had mastered both electric and acoustic guitar as well as the banjo.\n\nPrior to setting out as a solo artist, Meghan was the lead singer of the popular roots act The Stone Sparrows.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 23, 2016',
  //   title: 'Adam Baldwin',
  //   cost: '25',
  //   startTime: '9:30',
  //   youTube: [ 'ynKKAwXhfXM', 'YALS1sMzpwM' ],
  //   similarArtists:
  //    [ 'Firefly music project',
  //      'Sheena Harden',
  //      'Sharon Bee',
  //      'Nathan Town',
  //      'Jed Whedon' ],
  //   artistSummary: 'Adam Baldwin on tour with July Talk · Adam Baldwin \'Daylight\' music video' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/JamesVincentMcMorrow_Commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, November 24, 2016',
  //   title: 'Allan Rayman',
  //   cost: '32',
  //   startTime: '9:00',
  //   youTube: [ 'xGKIcgwlPPc', '_1hGPikXAaA' ],
  //   similarArtists:
  //    [ 'Johnny Rain',
  //      'RKCB',
  //      'Lawrence Taylor',
  //      'Francesco Yates',
  //      'Jahkoy' ],
  //   artistSummary: '..' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, November 25, 2016',
  //   title: 'Adam Baldwin',
  //   cost: '25',
  //   startTime: '9:30',
  //   youTube: [ 'ynKKAwXhfXM', 'YALS1sMzpwM' ],
  //   similarArtists:
  //    [ 'Firefly music project',
  //      'Sheena Harden',
  //      'Sharon Bee',
  //      'Nathan Town',
  //      'Jed Whedon' ],
  //   artistSummary: 'Adam Baldwin on tour with July Talk · Adam Baldwin \'Daylight\' music video' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, November 29, 2016',
  //   title: 'Lucie Silvas',
  //   cost: '32',
  //   startTime: '9:30',
  //   youTube: [ 'GlazjTgLN2M', 'byAGy_mFIdg' ],
  //   similarArtists:
  //    [ 'Delta Goodrem',
  //      'Nerina Pallot',
  //      'Amy Studt',
  //      'Sandi Thom',
  //      'Tina Arena' ],
  //   artistSummary: ' Lucie Silvas born 4 September 1977 in Kingston-Upon-Thames, London is a singer/songwriter from the United Kingdom. \n\nBorn Lucie Joanne Silverman. Lucie left school in the sixth form, where she became a backing vocalist for ex-Take That vocalist Gary Barlow and singer Judie Tzuke. In 2000 Lucie Silvas recorded her album "Forget Me Not" - with tracks including the single "It\'s Too Late". This song entered the charts with a low position, and Lucie was subsequently dropped from her record label.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 30, 2016',
  //   title: 'Lucie Silvas',
  //   cost: '32',
  //   startTime: '9:30',
  //   youTube: [ 'GlazjTgLN2M', 'byAGy_mFIdg' ],
  //   similarArtists:
  //    [ 'Delta Goodrem',
  //      'Nerina Pallot',
  //      'Amy Studt',
  //      'Sandi Thom',
  //      'Tina Arena' ],
  //   artistSummary: ' Lucie Silvas born 4 September 1977 in Kingston-Upon-Thames, London is a singer/songwriter from the United Kingdom. \n\nBorn Lucie Joanne Silverman. Lucie left school in the sixth form, where she became a backing vocalist for ex-Take That vocalist Gary Barlow and singer Judie Tzuke. In 2000 Lucie Silvas recorded her album "Forget Me Not" - with tracks including the single "It\'s Too Late". This song entered the charts with a low position, and Lucie was subsequently dropped from her record label.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/tdw_2016-scene-02_Scott_green-24-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, December 6, 2016',
  //   title: 'Telegram',
  //   cost: '32',
  //   startTime: '8:00',
  //   youTube: [ 'dloCmKoQoEA', 'IPvbMHP7Dzw' ],
  //   similarArtists:
  //    [ 'Sunflower Bean',
  //      'Mystery Jets',
  //      'Hooton Tennis Club',
  //      'Blossoms',
  //      'Eagulls' ],
  //   artistSummary: 'Telegram are a London based band formed in 2013. The band consists of Welsh frontman Matt Saunders, Matt Wood on guitar, Oli Paget-Moon on bass and Jordan Cook on drums. Influenced by their love of Eno, Syd Barrett, krautrock and late proto-punk, Telegram released their debut single "Follow" (B-side "Under The Night Time") on their own GramGram label in November 2013. \n\nTelegram have supported Franz Ferdinand, Manic Street Preachers and Temples in the past and are about to join Palma Violets on their upcoming tour in November. ' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Michael-Kiwanuka-Approved-Photo600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 7, 2016',
  //   title: 'Cloves',
  //   cost: '25',
  //   startTime: '8:00',
  //   youTube: [ 'F_Jk_uQ4gSg', '82CdBc0-Umw' ],
  //   similarArtists: [ 'Ofelia K', 'TransViolet', 'RKCB', 'kiiara', 'KIll J' ],
  //   artistSummary: 'http://cloves.bandcamp.com' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/06/AD-comm-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Monday, December 12, 2016',
  //   title: 'Chloe X Halle',
  //   cost: '30',
  //   startTime: '8:15',
  //   youTube: [ 'dvowOF4qrjQ', 'T0l6z0vH998' ],
  //   similarArtists: [ 'Solange', 'Beyoncé', 'Destiny\'s Child', 'Tinashe', 'Fantasia' ],
  //   artistSummary: 'Chloe and Halle Bailey (born July 1, 1998 and March 27, 2000 respectively) are American sisters, YouTube sensations, singers and actresses. Both born in Atlanta GA, they later moved to Los Angeles with their family to pursue music careers. In 2013, after their cover for "Pretty Hurts" went viral with nearly 12 million views, Beyoncé signed them to her management Parkwood Entertainment.[1] They were amongst the three talents she signed, others being Sophie Beem and Ingrid.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/InFlamesForgedinFireTour-approvedimage_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 14, 2016',
  //   title: 'HELLYEAH',
  //   cost: '42',
  //   startTime: '8:00',
  //   youTube: [ 'SBaIQreV8Yk', 'Y_nZfjZVaEg' ],
  //   similarArtists:
  //    [ 'Texas Hippie Coalition',
  //      'Damageplan',
  //      'DevilDriver',
  //      'Rebel Meets Rebel',
  //      'Five Finger Death Punch' ],
  //   artistSummary: 'Hellyeah is a rock band which formed in Dallas, Texas, United States in 2006. The band consists of Chad Grey (vocals), Greg Tribbett (guitar), Tom Maxwell (guitar), Bob Zilla (bass) and Vinnie Paul Abbott (drums). Grey and Tribbet are members of Mudvayne, Maxwell is a member of Nothingface, Zilla was a member of Damageplan and Abbott was a member of Pantera and Damageplan. The band has released two albums, "Hellyeah" (2007) and "Stampede" (2009).' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 21, 2016',
  //   title: 'Russ Liquid',
  //   cost: '30',
  //   startTime: '9:30',
  //   youTube: [ 'yiJne9h5G4c', '8DF1qQtzexc' ],
  //   similarArtists:
  //    [ 'Freddy Todd',
  //      'Gladkill',
  //      'Thriftworks',
  //      'MartyParty',
  //      'Vibesquad' ],
  //   artistSummary: 'Set apart from other up-and-coming West Coast bass music producers by his extensive world-touring history and performance experience, Russ Liquid brings a much-needed injection of melody and emotion to the thriving dance floor community. Classically trained on the piano, trumpet, saxophone and flute, Russ Liquid applies the colorful tones of instrumental music to the realm of beats with dance floor-rocking results. This talented producer has found an entirely new palette to “paint” with' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, December 22, 2016',
  //   title: 'Russ Liquid',
  //   cost: '30',
  //   startTime: '9:30',
  //   youTube: [ 'yiJne9h5G4c', '8DF1qQtzexc' ],
  //   similarArtists:
  //    [ 'Freddy Todd',
  //      'Gladkill',
  //      'Thriftworks',
  //      'MartyParty',
  //      'Vibesquad' ],
  //   artistSummary: 'Set apart from other up-and-coming West Coast bass music producers by his extensive world-touring history and performance experience, Russ Liquid brings a much-needed injection of melody and emotion to the thriving dance floor community. Classically trained on the piano, trumpet, saxophone and flute, Russ Liquid applies the colorful tones of instrumental music to the realm of beats with dance floor-rocking results. This talented producer has found an entirely new palette to “paint” with' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2014/11/Commodore-Thumbnail-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, December 31, 2016',
  //   title: 'SJS NYE 2017',
  //   cost: '40',
  //   startTime: '9:00',
  //   youTube: [],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 7, 2017',
  //   title: 'Jojo Mason',
  //   cost: '40',
  //   startTime: '9:00',
  //   youTube: [ 'u9z1yszloAE', 'OBKAisQOraI' ],
  //   similarArtists:
  //    [ 'PETRIC',
  //      'The Washboard Union',
  //      'James Barker Band',
  //      'River Town Saints',
  //      'Dan Davidson' ],
  //   artistSummary: 'Genre: Country Music Soul Music ..' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Sunday, January 8, 2017',
  //   title: 'Jojo Mason',
  //   cost: '40',
  //   startTime: '9:00',
  //   youTube: [ 'u9z1yszloAE', 'OBKAisQOraI' ],
  //   similarArtists:
  //    [ 'PETRIC',
  //      'The Washboard Union',
  //      'James Barker Band',
  //      'River Town Saints',
  //      'Dan Davidson' ],
  //   artistSummary: 'Genre: Country Music Soul Music ..' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Its-Just-Drag-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, January 13, 2017',
  //   title: 'It\'s Just Drag!',
  //   cost: '40',
  //   startTime: '9:00',
  //   youTube: [],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/BallroomBrawl7_600x500_Vancouver-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 14, 2017',
  //   title: 'ECCW Ballroom Brawl VII',
  //   cost: '20',
  //   startTime: '8:00',
  //   youTube: [ '_7X83_6Iyck', 'Q7xcnpc8bZ0' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/TheFighterAndTheKid_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, January 19, 2017',
  //   title: 'The Fighter and the Kid',
  //   cost: '25',
  //   startTime: '9:00',
  //   youTube: [ 'OdubY9b1Ud0', '-EojydAXveQ' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, January 20, 2017',
  //   title: 'Steel Panther',
  //   cost: '35',
  //   startTime: '9:00',
  //   youTube: [ 'G_vde4Ii8Ik', 'XXuN41avVRs' ],
  //   similarArtists: [ 'Mötley Crüe', 'Reckless Love', 'Warrant', 'Poison', 'Ratt' ],
  //   artistSummary: 'In 2008, Metal Skool changed their name to Steel Panther.\n\nSteel Panther is a Los Angeles, California based glam metal parody band founded by former LA Guns vocalist   Ralph Saenz  (Michael Starr). Originally formed as "Metal Skool" and "Metal Shop" they\'re known for their energetic live show, the longest running metal show on the Sunset Strip. On stage, the band both pays tribute to and lampoons the heyday of 80\'s glam metal. The band\'s between-song comedy includes jests at conflict between band members' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 21, 2017',
  //   title: 'Steel Panther',
  //   cost: '35',
  //   startTime: '9:00',
  //   youTube: [ 'G_vde4Ii8Ik', 'XXuN41avVRs' ],
  //   similarArtists: [ 'Mötley Crüe', 'Reckless Love', 'Warrant', 'Poison', 'Ratt' ],
  //   artistSummary: 'In 2008, Metal Skool changed their name to Steel Panther.\n\nSteel Panther is a Los Angeles, California based glam metal parody band founded by former LA Guns vocalist   Ralph Saenz  (Michael Starr). Originally formed as "Metal Skool" and "Metal Shop" they\'re known for their energetic live show, the longest running metal show on the Sunset Strip. On stage, the band both pays tribute to and lampoons the heyday of 80\'s glam metal. The band\'s between-song comedy includes jests at conflict between band members' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Sting600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, February 1, 2017',
  //   title: 'Joe Sumner',
  //   cost: '15',
  //   startTime: '8:00',
  //   youTube: [ 'QmW0cWNP8Eo', '2IMnwxWABQQ' ],
  //   similarArtists: [],
  //   artistSummary: 'Joseph Sumner (born 23 November 1976) is the son of actress Frances Tomelty and singer/actor/activist Gordon Sumner (known as Sting). He is the lead singer and bass player in the UK band Fiction Plane.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Sonreal-promo-photo_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, February 3, 2017',
  //   title: 'SonReal',
  //   cost: '20',
  //   startTime: '9:30',
  //   youTube: [ 'FyfjGuji3Wg', '_PyEkbj3UfA' ],
  //   similarArtists:
  //    [ 'Chris Webby',
  //      'SonReal & Rich Kidd',
  //      'Classified',
  //      'Kardinal Offishall',
  //      'OCD: Moosh & Twist' ],
  //   artistSummary: 'SonReal is a young and independent artist from Vancouver, B.C. Canada. With his humbling attitude and social awareness, SonReal brings a distinctive quality to the Hip-Hop genre. His mature self-understanding compels him to create a unique perspective contrary to the stereo-typical urban artist. His lyrics reflect real life issues, addressing topics such as poverty, education and social acceptance. Live instrumentals combined with natural vocal talent provide harmony and set SonReal apart from the average rapper.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/RBF600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, February 9, 2017',
  //   title: 'Ballyhoo!',
  //   cost: '27',
  //   startTime: '8:00',
  //   youTube: [],
  //   similarArtists:
  //    [ 'Passafire',
  //      'One Drop',
  //      'The Expendables',
  //      'Pepper',
  //      'Three Legged Fox' ],
  //   artistSummary: 'There are, at least, two groups by this name. Ballyhoo (without the exclamation mark!) is a South African group who had a huge hit in 1980 in their homeland with their single \'Man On The Moon\'. This South African group is still going strong. The other group with the same name (but with the exclamation mark!) is from Maryland, USA, a modern rock/reggae party band, active since 2006.\n\nBALLYHOO! is undeniably turning the world of music upside down and sideways as they blur the lines between rock' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/USS-image-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, February 10, 2017',
  //   title: 'Repartee',
  //   cost: '30',
  //   startTime: '9:00',
  //   youTube: [ 'ogzR6EhHiYQ', '7Ff9wmilVos' ],
  //   similarArtists:
  //    [ 'Matthew Hornell and The Diamond Minds',
  //      'Andrew James O\'Brien',
  //      'Motel Raphaël',
  //      'Jane\'s Party',
  //      'Beach Tiger' ],
  //   artistSummary: 'Repartee’s music has been described as ‘the kind of music that allows you to let loose while dancing, without giving a f*** about how foolish you look’ (the Muse). They play keyboard-based pop with elements of gritty rock. In a short period of time they’ve commanded a devoted following in St. John’s through their dynamic live show. It’s that sort of buzz that led to them receiving a MusicNL Professional Demo Grant to make their first EP, ‘Lost Like We All Are’.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, February 16, 2017',
  //   title: 'Craig Stickland',
  //   cost: '42',
  //   startTime: '9:00',
  //   youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
  //   similarArtists:
  //    [ 'Josh Auer',
  //      'Bryce Jardine',
  //      'Mark Diamond',
  //      'Rebecca Roubion',
  //      'Taylor  Mathews' ],
  //   artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, February 17, 2017',
  //   title: 'Craig Stickland',
  //   cost: '42',
  //   startTime: '9:00',
  //   youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
  //   similarArtists:
  //    [ 'Josh Auer',
  //      'Bryce Jardine',
  //      'Mark Diamond',
  //      'Rebecca Roubion',
  //      'Taylor  Mathews' ],
  //   artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/MattGood_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, February 18, 2017',
  //   title: 'Craig Stickland',
  //   cost: '42',
  //   startTime: '9:00',
  //   youTube: [ 'R3EkgD9CXBk', 'JDX_iVk2cMU' ],
  //   similarArtists:
  //    [ 'Josh Auer',
  //      'Bryce Jardine',
  //      'Mark Diamond',
  //      'Rebecca Roubion',
  //      'Taylor  Mathews' ],
  //   artistSummary: 'Music video by Craig Stickland performing Liquor Store Blues' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2014/11/Commodore-Thumbnail-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, March 4, 2017',
  //   title: 'Borgore',
  //   cost: '30',
  //   startTime: '9:00',
  //   youTube: [ 'Hr1Vlodqh90', 'iRF4Li02_pU' ],
  //   similarArtists: [ 'Doctor P', 'Datsik', 'Cookie Monsta', 'Flux Pavilion', 'Eptic' ],
  //   artistSummary: 'Borgore is the alias of Israeli dubstep producer Asaf Borger, who is currently releasing tunes through Shift Recordings, Terminal Dusk, Trill Bass, Zaudio, Mad Decent, and Sumerian records He is also a drummer for the deathcore band Shabira , and part of the dubstep duo Alphamale Primates, which consists of him and Tomba.\n\nHe has recently finished a massive US tour to sold out dates everywhere and a plethora of positive reviews. Borgore has also promoted' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/cadillacthreeTM-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, March 8, 2017',
  //   title: 'The Cadillac Three',
  //   cost: '27',
  //   startTime: '9:30',
  //   youTube: [ 'KLLp7jbQaYY', 'yb7iP-A6NHI' ],
  //   similarArtists:
  //    [ 'Blackberry Smoke',
  //      'Whiskey Myers',
  //      'Blackfoot',
  //      'Black Stone Cherry',
  //      'Monster Truck' ],
  //   artistSummary: 'The Cadillac Three, originally known as Cadillac Black, is an American country music group consisting of Jaren Johnston (lead vocals, guitar), Kelby Ray (bass guitar, Dobro, acoustic guitar, vocals), and Neil Mason (drums, vocals).' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Blackie-and-the-Rodeo-Kings-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, March 10, 2017',
  //   title: 'An Evening with Blackie and The Rodeo Kings',
  //   cost: '45',
  //   startTime: '9:00',
  //   youTube: [ 'FaVjFNJIxfU', 'acJhHs8HsRs' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Japandroids305x225-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Monday, March 20, 2017',
  //   title: 'Craig Finn',
  //   cost: '25',
  //   startTime: '9:30',
  //   youTube: [ 'JaUJnPWeBKc', '1brqbaX5xiI' ],
  //   similarArtists:
  //    [ 'The Hold Steady',
  //      'Jason Isbell',
  //      'Cory Branan',
  //      'Josh Ritter',
  //      'Dave Hause' ],
  //   artistSummary: 'Craig Finn is the man behind Lifter Puller, The Brokerdealer and The Hold Steady.  He was also featured on Rhymesayers rapper P.O.S.\'s Safety In Speed (Heavy Metal).  He released his first solo album,  Clear Heart Full Eyes, on January of 2012.\n\nHere is some background information on Clear Heart Full Eyes from the  No Future Songfacts . In early 2011 Hold Steady frontman Craig Finn challenged himself to write a new song every day in his Brooklyn apartment for his first solo album.' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, March 31, 2017',
  //   title: 'The Tea Party #TX20',
  //   cost: '39',
  //   startTime: '9:30',
  //   youTube: [ 'YfaATa-qmG4', 'JCye7v79Tz0' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, April 1, 2017',
  //   title: 'The Tea Party #TX20',
  //   cost: '39',
  //   startTime: '9:30',
  //   youTube: [ 'YfaATa-qmG4', 'JCye7v79Tz0' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/The-Damned-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, April 15, 2017',
  //   title: 'The Damned: 40th Anniversary U.S. Tour',
  //   cost: '29',
  //   startTime: '9:00',
  //   youTube: [ 'w1wbX3mICqw', 'cqCbdLXkLTI' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Zombies_Image_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, April 21, 2017',
  //   title: 'The Zombies: Odessey & Oracle 50th Anniversary',
  //   cost: '45',
  //   startTime: '9:00',
  //   youTube: [ 'goDxhJl1UJE', 'AL6K-acL2BU' ],
  //   similarArtists: [] },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/bonobo305-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, May 24, 2017',
  //   title: 'Bonobo',
  //   cost: '35',
  //   startTime: '8:00',
  //   youTube: [ 'fQAFfeQNpGc', 'tUzY3zc9vs8' ],
  //   similarArtists:
  //    [ 'Emancipator',
  //      'Blockhead',
  //      'Thievery Corporation',
  //      'The Cinematic Orchestra',
  //      'Mechanical Me' ],
  //   artistSummary: 'Simon Green AKA Bonobo\'s first album - 2000\'s \'Animal Magic\' - was released via Tru Thoughts before being picked up by Ninja Tune. It announced him as a serious talent; able to bring a musician\'s edge to electronic music, with all the freedom that skill allowed. His subsequent albums for Ninja, Dial M for Monkey and Days to Come, developed his sensibility, won him fans across the globe, and saw him develop his live show into a mesmeric re-working of his records. ' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/bonobo600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, May 25, 2017',
  //   title: 'Bonobo',
  //   cost: '35',
  //   startTime: '8:00',
  //   youTube: [ 'fQAFfeQNpGc', 'tUzY3zc9vs8' ],
  //   similarArtists:
  //    [ 'Emancipator',
  //      'Blockhead',
  //      'Thievery Corporation',
  //      'The Cinematic Orchestra',
  //      'Mechanical Me' ],
  //   artistSummary: 'Simon Green AKA Bonobo\'s first album - 2000\'s \'Animal Magic\' - was released via Tru Thoughts before being picked up by Ninja Tune. It announced him as a serious talent; able to bring a musician\'s edge to electronic music, with all the freedom that skill allowed. His subsequent albums for Ninja, Dial M for Monkey and Days to Come, developed his sensibility, won him fans across the globe, and saw him develop his live show into a mesmeric re-working of his records. ' },
  // { date: 'Tuesday November 22nd ',
  //   title: 'Mr Little Jeans',
  //   cost: '18',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/mr-little-jeans/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/MrLittleJeansPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/174735252965763/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ '90CGCzBs3gQ', 'oB13wqesv_g' ],
  //   similarArtists: [],
  //   artistSummary: 'Mr. Little Jeans, a singer deep deep from the Norwegian woods, currently based between Stockholm & LA' },
  // { date: 'Thursday November 24th ',
  //   title: 'Van Damsel',
  //   cost: '12',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/van-damsel/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/VanDamselPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/1289733651066291/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'A-YHP3rf5Js', 'gbdleQUSUfc' ],
  //   similarArtists:
  //    [ 'Sun Culture',
  //      'Fine Times',
  //      'Kiki Rowe',
  //      'Black Black Hills',
  //      'Head Of The Herd' ],
  //   artistSummary: 'Van Damsel is a guitar-driven indie-rock act with a modern edge, combining an upbeat, danceable, and hard-hitting sound with ambient, emotional textures and highly relatable lyrics.' },
  // { date: 'Friday November 25th ',
  //   title: 'TUNS',
  //   cost: '15',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/tuns/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/TunsPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/561440730724093/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'ZG3JXEJLXnM', 'euhknTzBe8o' ],
  //   similarArtists:
  //    [ 'The Damn Truth',
  //      'Only Yours',
  //      'Your Boy Tony Braxton',
  //      'The StandStills',
  //      'Dawg Yawp' ],
  //   artistSummary: 'Top Hits Who cares about the chart order, less rap & more hits! 80s Hits Hear \nyour classic favorites right here! Soft Rock The best in Soft Rock music!' },
  // { date: 'Saturday November 26th ',
  //   title: 'Paper Lions',
  //   cost: '14',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/paper-lions/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/PaperLionsPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/1773006039612600/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'Q1sHvKfKFZs', 'etCGZos14S4' ],
  //   similarArtists:
  //    [ 'Said the Whale',
  //      'Two Hours Traffic',
  //      'Hey Rosetta!',
  //      'The Zolas',
  //      'Arkells' ],
  //   artistSummary: '(1)  Hailing from the unlikely small community of Belfast, Prince Edward Island, brothers John and Rob MacPhee and neighbour Colin Buchanan began playing music together at a very young age in a variety of garage bands. After meeting in high school, David Cyrus MacDonald was recruited and Paper Lions cemented with John and Rob filling the positions of lead vocals and bass respectively, Colin on lead guitar and David on drums. \n\nAfter the release of their critically acclaimed' },
  // { date: 'Sunday November 27th ',
  //   title: 'Kitty Nights\' Fall Burlesque Showcase!',
  //   cost: '10',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/kitty-nights-fall-burlesque-showcase/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14494661_1217017791702679_6483826289690522254_n.jpg',
  //   fb: 'https://www.facebook.com/events/107631692996243/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [],
  //   similarArtists: [] },
  // { date: 'Wednesday November 30th ',
  //   title: 'CRX',
  //   cost: '15',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/crx/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14484607_10154703345994255_2481276756092808628_n.jpg',
  //   fb: 'https://www.facebook.com/events/998397083603040/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'yquKa6GJ8i8', 'KsXYnhNXUb8' ],
  //   similarArtists:
  //    [ 'The Strokes',
  //      'Vant',
  //      'Beware of Darkness',
  //      'Deap Vally',
  //      'The Kills' ],
  //   artistSummary: 'The Strokes\' Nick Valensi project, CRX other members are Ralph Alexander (The Dose), Richie Follin (Guards), Darian Zahedi, and Jon Safley (The Reflections).' },
  // { date: 'Tuesday December 6th ',
  //   title: 'Wild Child',
  //   cost: '49',
  //   startTime: 'Not Available',
  //   link: 'http://biltmorecabaret.com/events/wild-child/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/WILD-CHILD-APPROVED-PHOTO-1-1024x689.jpg',
  //   fb: 'https://www.facebook.com/events/1143044845716045/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ '878_AiEkU4s', 'n-qpJ0owFcc' ],
  //   similarArtists:
  //    [ 'Phox',
  //      'The Oh Hellos',
  //      'The Lighthouse and the Whaler',
  //      'Blind Pilot',
  //      'Hey Marseilles' ],
  //   artistSummary: 'There are 4 active bands using the name Wild Child.\n\n1. A six-piece indie folk band from Austin, TX. \nMembers are: primary singers/songwriters Kelsey Wilson and Alexander Beggins, drummer Carey McGraw, cellist Sadie Wolfe, keyboardist Evan Magers and bassist Chris D\'Annunzio They are managed by Pat Cassidy.\nTheir first album, the 15-track Pillow Talk, was released on October 25, 2011 with help from San Francisco producers Evan Magers and Alex Peterson, and mastered by Erik Wofford).' },
  // { date: 'Saturday December 10th ',
  //   title: 'Mia Stammer + Adelaine Morin: Vancouver',
  //   cost: '15',
  //   startTime: '30',
  //   link: 'http://biltmorecabaret.com/events/mia-stammer-adelaine-morin-vancouver/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Mia-1024x1024.jpg',
  //   fb: 'https://www.facebook.com/events/158033394656968/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [],
  //   similarArtists: [] },
  // { date: 'Saturday December 17th ',
  //   title: 'COASTLINE PILOT',
  //   cost: '18',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/coastline-pilot/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/coastlinevaultryjaketouzelinsta-1024x1024.jpg',
  //   fb: 'https://www.facebook.com/events/189497901509330/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'mJDkCcwAQEk', '21lwh4GR1Qk' ],
  //   similarArtists: [],
  //   artistSummary: 'Coastline Pilot ..' },
  // { date: 'Monday January 16th ',
  //   title: 'John Paul White',
  //   cost: '18',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/john-paul-white/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/John-Paul-White-Approved-Photo-1-1024x768.jpg',
  //   fb: 'https://www.facebook.com/events/1792909857638054/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'dxpuM4OIvgo', 'GpzSViue1SM' ],
  //   similarArtists:
  //    [ 'Lera Lynn',
  //      'The Civil Wars',
  //      'Lori McKenna',
  //      'Alexandra Savior',
  //      'Aoife O\'Donovan' ],
  //   artistSummary: 'From deep in inland Alabama comes a talent so effortless and sincere that it is a wonder why the big wigs didn\'t jump on him sooner. John Paul White, who has recently signed with mega-label Capitol Records, relies mostly on his acoustic guitar to build his songs - but has no problems dressing them up with melodic electric guitar lines. I know I\'m always pulling the dramatics out of my hat, but these songs really are achingly beautiful. I hope you\'ll hear more from JPW in the future as he records his new disc for Capitol.' },
  // { date: 'Thursday February 2nd ',
  //   title: 'Lydia Loveless',
  //   cost: '20',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/lydia-loveless/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/15003365_1011783955610301_6933406659675946928_o-683x1024.jpg',
  //   fb: 'http://biltmorecabaret.com/concerts/facebook.com/events/1775334666051468/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ '3XyKhTwk9X8', 'YPk2I475zOY' ],
  //   similarArtists:
  //    [ 'Nikki Lane',
  //      'Amanda Shires',
  //      'John Moreland',
  //      'Drive-By Truckers',
  //      'Robbie Fulks' ],
  //   artistSummary: 'Blessed with a commanding, blast-it-to-the-back-of-the room voice, the 24-year-old Lydia Loveless was raised on a family farm in Coshocton, Ohio, US—a small weird town with nothing to do but make music. With a dad who owned a country music bar, Loveless often woke up with a house full of touring musicians scattered on couches and floors.\n\nWhen she got older, in the time-honored traditions of teenage rebellion, she turned her back on these roots' },
  // { date: 'Thursday February 16th ',
  //   title: 'CLOUD NOTHINGS',
  //   cost: undefined,
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/cloud-nothings/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/CloudNothings2017_PressPhoto-1024x1024.jpg',
  //   fb: 'https://www.facebook.com/pg/biltmorecabaret/events/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'YRR2c4akWjw', 'rt9N_yHvwyM' ],
  //   similarArtists:
  //    [ 'Japandroids',
  //      'Wavves',
  //      'Wavves X Cloud Nothings',
  //      'Cymbals Eat Guitars',
  //      'Yuck' ],
  //   artistSummary: 'Cloud Nothings is an indie rock band from Cleveland, Ohio. Dylan Baldi started Cloud Nothings as a way to amuse himself between classes at Case Western Reserve University in 2009. The first batch of Cloud Nothings songs, including the blogosphere favorite "Hey Cool Kid" (available on the 2010 compilation "Turning On"), was recorded on a computer in the basement of Baldi\'s home in Westlake, OH. A concert promoter who invited Cloud Nothings to play' },
  // { date: 'Wednesday February 22nd ',
  //   title: 'clipping',
  //   cost: undefined,
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/clipping/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Tennis_Press-1024x728.jpg',
  //   fb: 'https://www.facebook.com/events/1780034532213944/',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ '_nibVU1RjAM', 'B6Xt5K66dHk' ],
  //   similarArtists: [],
  //   artistSummary: 'There are several artist named "clipping".\n\nFor the LA rap trio, please see clipping.' },
  // { date: 'Wednesday March 1st ',
  //   title: 'Tennis with guests',
  //   cost: undefined,
  //   startTime: undefined,
  //   link: 'http://biltmorecabaret.com/events/tennis-with-guests/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Joseph_credit_Ebru_Yildiz-1024x579.jpg',
  //   fb: 'https://www.facebook.com/events/1104129646368219/?notif_t=plan_admin_added&notif_id=1478016004034011#',
  //   venue: 'Biltmore Cabaret',
  //   youTube: [ 'Px9biv1pgVE', 'RWJoaWQmraM' ],
  //   similarArtists: [] } ]

module.exports = shows;
