const shows = [ { date: 'Thursday November 10th ',
    title: 'Rykka',
    cost: '12',
    startTime: '7',
    link: 'http://biltmorecabaret.com/events/rykka/',
    photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/10/rykka-instagram.png',
    fb: 'https://www.facebook.com/events/1121331827960263/',
    youTube: ['https://www.youtube.com/embed/YTxLRRDkBjw', 'https://www.youtube.com/embed/dsmxU8RImR0', 'https://www.youtube.com/embed/0uuXil0KcBM'] ,
    venue: 'Biltmore Cabaret' },
  { date: 'Friday November 11th ',
    title: 'Bully',
    cost: '15',
    startTime: '7',
    link: 'http://biltmorecabaret.com/events/bully/',
    photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/13686641_914698858652145_1513348522314762078_n.jpg',
    fb: 'https://www.facebook.com/events/1785401611740018/',
    youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
    venue: 'Biltmore Cabaret' },
  { date: 'Saturday November 12th ',
    title: 'Dune Rats',
    cost: '14',
    startTime: '7',
    link: 'http://biltmorecabaret.com/events/dune-rats-and-dz-deathrays-death-rats-tour/',
    photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/dune_rats_foto_WEB.jpg',
    fb: 'https://www.facebook.com/events/318075835208861/',
    youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
    venue: 'Biltmore Cabaret' },
    { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/The-Trews-Photo-230x170.jpg',
      link: 'http://www.commodoreballroom.com/calendar/',
      venue: 'Commodore Ballroom',
      date: 'Saturday, November 12, 2016',
      title: 'Bleeker',
      cost: '32',
      youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
      startTime: '9:30' },
    { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/Yelawolf-Commodore-230x170.jpg',
      link: 'http://www.commodoreballroom.com/calendar/',
      venue: 'Commodore Ballroom',
      date: 'Sunday, November 13, 2016',
      title: 'Bubba Sparxxx',
      youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
      cost: '42',
      startTime: '9:00' },
    { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/torylanez-commodore-230x170.jpg',
      link: 'http://www.commodoreballroom.com/calendar/',
      venue: 'Commodore Ballroom',
      date: 'Tuesday, November 15, 2016',
      youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
      title: 'Jacquees',
      cost: '36',
      startTime: '9:00' },
    { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/animalsasleaders_commodore-230x170.jpg',
      link: 'http://www.commodoreballroom.com/calendar/',
      venue: 'Commodore Ballroom',
      date: 'Wednesday, November 16, 2016',
      title: 'Intervals, Plini',
      cost: '25',
      youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
      startTime: '8:00' },
    { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/PortugalTheMan_commodore-230x170.jpg',
      link: 'http://www.commodoreballroom.com/calendar/',
      venue: 'Commodore Ballroom',
      date: 'Thursday, November 17, 2016',
      title: 'Boone Howard',
      youTube: ['https://www.youtube.com/embed/cgzWHjq-Dsg', 'https://www.youtube.com/embed/ULYTqO2YDuU', 'https://www.youtube.com/embed/r7LLBBGOfKY'],
      cost: '29',
      startTime: '9:30' },
  ]


  // { date: 'Tuesday November 15th ',
  //   title: 'Mouse on the Keys + LITE',
  //   cost: '20',
  //   startTime: 'Not Available',
  //   link: 'http://biltmorecabaret.com/events/mouse-on-the-keys-lite/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/LiteMouseOnTheKeysPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/1749252875330064/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Wednesday November 16th ',
  //   title: 'Jenny Hval',
  //   cost: '14',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/jenny-hval/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/JennyHvalPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/281636798852111/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Friday November 18th ',
  //   title: 'Waterstrider',
  //   cost: '12',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/waterstrider/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14199700_10154591076269255_8497776674501552069_n.jpg',
  //   fb: 'https://www.facebook.com/events/1730660833817418/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Tuesday November 22nd ',
  //   title: 'Mr Little Jeans',
  //   cost: '18',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/mr-little-jeans/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/MrLittleJeansPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/174735252965763/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Thursday November 24th ',
  //   title: 'Van Damsel',
  //   cost: '12',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/van-damsel/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/VanDamselPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/1289733651066291/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Friday November 25th ',
  //   title: 'TUNS',
  //   cost: '15',
  //   startTime: '7',
  //   link: 'http://biltmorecabaret.com/events/tuns/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/TunsPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/561440730724093/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Saturday November 26th ',
  //   title: 'Paper Lions',
  //   cost: '14',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/paper-lions/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/PaperLionsPoster-663x1024.jpg',
  //   fb: 'https://www.facebook.com/events/1773006039612600/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Sunday November 27th ',
  //   title: 'Kitty Nights\' Fall Burlesque Showcase!',
  //   cost: '10',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/kitty-nights-fall-burlesque-showcase/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14494661_1217017791702679_6483826289690522254_n.jpg',
  //   fb: 'https://www.facebook.com/events/107631692996243/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Wednesday November 30th ',
  //   title: 'CRX',
  //   cost: '15',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/crx/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/14484607_10154703345994255_2481276756092808628_n.jpg',
  //   fb: 'https://www.facebook.com/events/998397083603040/',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Wednesday March 1st ',
  //   title: 'Tennis with guests',
  //   cost: '18',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/tennis-with-guests/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/Tennis_Press-1024x728.jpg',
  //   fb: 'https://www.facebook.com/events/1104129646368219/?notif_t=plan_admin_added&notif_id=1478016004034011#',
  //   venue: 'Biltmore Cabaret' },
  // { date: 'Wednesday April 26th ',
  //   title: 'The Wedding Present',
  //   cost: '20',
  //   startTime: '8',
  //   link: 'http://biltmorecabaret.com/events/the-wedding-present/',
  //   photo: 'http://biltmorecabaret.com/wp-content/uploads/2016/11/theweddingpresentpress-1024x733.jpg',
  //   fb: 'https://www.facebook.com/events/361969300807119',
  //   venue: 'Biltmore Cabaret' } ]
  //   .concat([ { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/06/Shovels-Rope-Press-Photocommodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 9, 2016',
  //   title: 'Indianola',
  //   cost: '25',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/KEYS-N-KRATES600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, November 10, 2016',
  //   title: 'Keys N Krates',
  //   cost: '25',
  //   startTime: 'Not Available' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/LAPSLEY-commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, November 11, 2016',
  //   title: 'Aquilo',
  //   cost: '22',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/The-Trews-Photo-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, November 12, 2016',
  //   title: 'Bleeker',
  //   cost: '32',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/Yelawolf-Commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Sunday, November 13, 2016',
  //   title: 'Bubba Sparxxx',
  //   cost: '42',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/torylanez-commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, November 15, 2016',
  //   title: 'Jacquees, Kranium, Taylor Bennett, VeeCee',
  //   cost: '36',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/animalsasleaders_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 16, 2016',
  //   title: 'Intervals, Plini',
  //   cost: '25',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/PortugalTheMan_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, November 17, 2016',
  //   title: 'Boone Howard',
  //   cost: '29',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/ATribeCalledRed_TM_2426x1365_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, November 18, 2016',
  //   title: 'Saul Williams',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/Wintersleep-Photo-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, November 19, 2016',
  //   title: 'Fake Palms',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/ATribeCalledRed_TM_2426x1365_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Monday, November 21, 2016',
  //   title: 'OKA, Saul Williams',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/GordBamford_IG_1080x1080_Vancouver600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, November 22, 2016',
  //   title: 'Meghan Patrick',
  //   cost: '30',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 23, 2016',
  //   title: 'Adam Baldwin, MONA',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/JamesVincentMcMorrow_Commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, November 24, 2016',
  //   title: 'Allan Rayman',
  //   cost: '32',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/20160629commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, November 25, 2016',
  //   title: 'Adam Baldwin, MONA',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, November 29, 2016',
  //   title: 'Lucie Silvas',
  //   cost: '32',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/08/BrothersOsborne_IG_commodore-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, November 30, 2016',
  //   title: 'Lucie Silvas',
  //   cost: '32',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/07/tdw_2016-scene-02_Scott_green-24-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Tuesday, December 6, 2016',
  //   title: 'Telegram',
  //   cost: '32',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Michael-Kiwanuka-Approved-Photo600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 7, 2016',
  //   title: 'Cloves',
  //   cost: '25',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/06/AD-comm-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Monday, December 12, 2016',
  //   title: 'Chloe X Halle',
  //   cost: '30',
  //   startTime: '8:15' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/09/InFlamesForgedinFireTour-approvedimage_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 14, 2016',
  //   title: 'HELLYEAH',
  //   cost: '42',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Wednesday, December 21, 2016',
  //   title: 'Funk the Halls with The Funk Hunters',
  //   cost: '30',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/FunkHunters_600x500-1-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, December 22, 2016',
  //   title: 'Funk the Halls with The Funk Hunters',
  //   cost: '30',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2014/11/Commodore-Thumbnail-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, December 31, 2016',
  //   title: 'SJS NYE 2017',
  //   cost: '40',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 7, 2017',
  //   title: 'Tim Hicks & Chad Brownlee',
  //   cost: '40',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/timhicks_Chadbrownlee_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Sunday, January 8, 2017',
  //   title: 'Tim Hicks & Chad Brownlee',
  //   cost: '40',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/BallroomBrawl7_600x500_Vancouver-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 14, 2017',
  //   title: 'ECCW Ballroom Brawl VII',
  //   cost: '20',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, January 20, 2017',
  //   title: 'Steel Panther',
  //   cost: '35',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/SteelPanther_600x500_photo_only-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, January 21, 2017',
  //   title: 'Steel Panther',
  //   cost: '35',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Sonreal-promo-photo_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, February 3, 2017',
  //   title: 'SonReal',
  //   cost: '20',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/RBF600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, February 9, 2017',
  //   title: 'Ballyhoo!, Pkew Pkew Pkew',
  //   cost: '27',
  //   startTime: '8:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/USS-image-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, February 10, 2017',
  //   title: 'Repartee',
  //   cost: '30',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/Japandroids305x225-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Monday, March 20, 2017',
  //   title: 'Craig Finn',
  //   cost: '25',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, March 31, 2017',
  //   title: 'The Tea Party #TX20',
  //   cost: '39',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Tea-Party-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, April 1, 2017',
  //   title: 'The Tea Party #TX20',
  //   cost: '39',
  //   startTime: '9:30' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/The-Damned-600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Saturday, April 15, 2017',
  //   title: 'The Damned: 40th Anniversary U.S. Tour',
  //   cost: '29',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/10/Zombies_Image_600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Friday, April 21, 2017',
  //   title: 'The Zombies: Odessey & Oracle 50th Anniversary',
  //   cost: '45',
  //   startTime: '9:00' },
  // { photo: 'http://www.commodoreballroom.com/wp-content/uploads/2016/11/bonobo600x500-230x170.jpg',
  //   link: 'http://www.commodoreballroom.com/calendar/',
  //   venue: 'Commodore Ballroom',
  //   date: 'Thursday, May 25, 2017',
  //   title: 'Bonobo',
  //   cost: '35',
  //   startTime: '8:00' } ]);

export default shows;
